[Bug]: Video Vimeo and Dailymotion not work
pimcore/pimcore pull request #10182
Opened 2021-08-27 12:22 UTC by mediafant

Vimeo, Dailymotion

  
  

## Changes in this pull request  
Resolves #10152

## Additional info

2021-08-31 05:41 UTC, dvesh3 commented
@mediafant please rebase on 10.x to fix phpstan failed tests. thanks!

2021-09-03 05:38 UTC, dvesh3 requested changes
@mediafant please see request changes and rebase this PR on branch 10.1. thanks!

2021-09-03 05:38 UTC, dvesh3 commented on models/Document/Editable/Video.php
> +            if (array_key_exists('width', $config)) {
default value should be used if null is passed in width so we should revert back to null coalescing

2021-09-03 05:38 UTC, dvesh3 commented on models/Document/Editable/Video.php
> +            if (array_key_exists('height', $config)) {
default value should be used if null is passed in height

2021-09-03 05:38 UTC, dvesh3 commented on models/Document/Editable/Video.php
> +            if (array_key_exists('dailymotion', $config) && is_array($config['dailymotion'])) {
```suggestion
            if (isset($config['dailymotion']) && is_array($config['dailymotion'])) {
```

2021-09-08 05:44 UTC, dvesh3 commented
@mediafant please see my comments above

2021-09-13 07:47 UTC, brusch commented
@mediafant 🏓 `10.1.3`is going to be released this Wednesday, so it would be good to have this done by tomorrow 😉). Thanks a lot!

2021-09-22 08:14 UTC, dvesh3 commented
closed in favor of #10370

2021-09-22 08:14 UTC, closed without merging