Add foreign keys to data store tables
pimcore/pimcore pull request #10486
Opened 2021-10-04 06:38 UTC by BlackbitNeueMedien

From time to time we have the problem that there is an item in the `object_store_*` table but not in `objects`. As there is a unique data field it is neither possible to create a new item with the same value, not to find the existing one (because of INNER JOINS on the `objects` table. I do not know the reason, perhaps there is a transaction missing somewhere but anyway, it would be cleaner if the data which belongs together would be explicitly connected with a foreign key. Then such situations could not occur anymore, no matter how one of the datasets belonging to the same object got removed / not created.

2021-10-04 08:30 UTC, brusch commented
@BlackbitNeueMedien I agree, that totally makes sense! 
Just some more thoughts on it: 
- we should implement it consistently across all object related tables, so including localized fields, object bricks and field collections
- I think we can remove `ON UPDATE` as updating the ID is anyway not supported
- we should create migrations for existing tables
- we should remove resulting obsolete code 

For now I'd focus on data objects, then we could and should extend it at least to all other entities (Documents & Assets).

2021-10-18 11:24 UTC, BlackbitDevs commented
Is now implemented for all data object-related tables.
I removed the "ON UPDATE CASCADE" (as @brusch mentioned)
Wrote a migration for existing tables.
Removed now unnecessary deletion of object-related data as this now gets automatically deleted via foreign keys.

2021-10-19 14:56 UTC, brusch requested changes

2021-10-19 14:56 UTC, brusch commented on bundles/CoreBundle/Migrations/Version20211018104331.php
> +                    if($tableSchema->getColumn($objectIdColumn)->getCustomSchemaOption('unsigned') === false) {
```suggestion
                    $column = $tableSchema->getColumn($objectIdColumn);
                    if(!$column->hasCustomSchemaOption('unsigned') || $column->getCustomSchemaOption('unsigned') === false) {
```
Otherwise this would result in `Warning: Undefined array key "unsigned" `

2021-10-19 14:56 UTC, brusch commented on bundles/CoreBundle/Migrations/Version20211018104331.php
> +            'object_localized_data_'.$class->getId() => 'ooo_id'
`object_localized_query_*` tables are missing here.

2021-10-19 14:56 UTC, brusch commented on bundles/CoreBundle/Migrations/Version20211018104331.php
> +                    $tableSchema->addForeignKeyConstraint('objects', [$objectIdColumn], ['o_id'], ['ON DELETE CASCADE'], $fkName);
```suggestion
                    $tableSchema->addForeignKeyConstraint('objects', [$objectIdColumn], ['o_id'], ['onDelete' => 'CASCADE'], $fkName);
```
The current code however adds the FK, but with default action `RESTRICT`.

2021-10-19 14:56 UTC, brusch commented on bundles/CoreBundle/Migrations/Version20211018104331.php
> +                $fkName = 'fk_'.$table.'__'.$objectIdColumn;
```suggestion
                $fkName = AbstractDao::getForeignKeyName($table, $objectIdColumn);
```

2021-10-19 14:56 UTC, brusch commented on bundles/CoreBundle/Migrations/Version20211018104331.php
> +            $foreignKeys['object_brick_query_'.$brickDefinition->getKey().'_'.$class->getId()] = 'o_id';
`object_brick_store_*` tables are missing here.

2021-10-19 14:56 UTC, brusch commented on bundles/CoreBundle/Migrations/Version20211018104331.php
> +            'object_query_'.$class->getId() => 'oo_id',
Additionally we should also add `object_url_slugs.objectId` , this also needs to be considered in `install.sql`.

2021-10-19 14:56 UTC, brusch commented on models/DataObject/Concrete/Dao.php
> -                    $fd->delete($this->model);
This needs to stay, because there could be data-types which are e.g. not using the database at all but e.g. Redis.

2021-10-19 14:56 UTC, brusch commented on models/DataObject/ClassDefinition/Dao.php
> +			  CONSTRAINT `".self::getForeignKeyName($objectDatastoreTableRelation, 'src_id')."` FOREIGN KEY (`src_id`) REFERENCES objects (`o_id`) ON DELETE CASCADE
We could do that for `dest_id` column as well, right?

2021-10-20 05:49 UTC, BlackbitDevs commented on bundles/CoreBundle/Migrations/Version20211018104331.php
> +            $foreignKeys['object_brick_query_'.$brickDefinition->getKey().'_'.$class->getId()] = 'o_id';
Fixed.

2021-10-20 05:49 UTC, BlackbitDevs commented on bundles/CoreBundle/Migrations/Version20211018104331.php
> +            'object_localized_data_'.$class->getId() => 'ooo_id'
Fixed.

2021-10-20 05:49 UTC, BlackbitDevs commented on bundles/CoreBundle/Migrations/Version20211018104331.php
> +            'object_query_'.$class->getId() => 'oo_id',
Fixed.

2021-10-20 05:49 UTC, BlackbitDevs commented on models/DataObject/Concrete/Dao.php
> -                    $fd->delete($this->model);
Fixed.

2021-10-20 05:57 UTC, BlackbitDevs commented on models/DataObject/ClassDefinition/Dao.php
> +			  CONSTRAINT `".self::getForeignKeyName($objectDatastoreTableRelation, 'src_id')."` FOREIGN KEY (`src_id`) REFERENCES objects (`o_id`) ON DELETE CASCADE
I think this is not possible because `dest_id` could also refer to assets or documents. 

Edit: This seems to be named `polymorphic foreign key` and it is [possible](https://stackoverflow.com/questions/2002985/mysql-conditional-foreign-key-constraints#67708114) but this seems to get too complicated imho. Also I do not know if all supported DBMS vendors support such *generated columns*. What do you think, @brusch ?

2021-10-20 06:56 UTC, brusch commented on models/DataObject/ClassDefinition/Dao.php
> +			  CONSTRAINT `".self::getForeignKeyName($objectDatastoreTableRelation, 'src_id')."` FOREIGN KEY (`src_id`) REFERENCES objects (`o_id`) ON DELETE CASCADE
@BlackbitNeueMedien you're right, I'd leave it as it is for now. Thanks a lot for your changes 😊

2021-10-20 09:09 UTC, brusch commented on lib/Model/Dao/AbstractDao.php
> +            $fkName = 'fk_'.md5($fkName);
```suggestion
            $fkName = substr($fkName, 0, 55) . '_' . hash('crc32', $fkName);
```
I think keeping a prefix here would be nice and `crc32` should be enough randomness.

2021-10-20 09:39 UTC, merged

2021-10-20 09:39 UTC, brusch commented
Well done 👍 Thanks a lot!