[Data Objects] Text Layout - Add option to define content via twig
pimcore/pimcore pull request #10502
Opened 2021-10-05 12:25 UTC by dvesh3

## Changes in this pull request  
Resolves #9547

## Additional info

2021-10-08 08:17 UTC, fashxp requested changes

2021-10-08 08:17 UTC, fashxp commented on bundles/AdminBundle/Controller/Admin/DataObject/ClassController.php
> +        $obj = DataObject::getByPath($objPath) ?? new DataObject\Concrete();
any change to instantiate the correct class and not concrete ... otherwise we will get error messages like the following, as the specific methods do not exist: 
![image](https://user-images.githubusercontent.com/8792145/136520524-c1a473f5-fb98-41b6-a38e-ce396ffb2601.png)

2021-10-08 08:17 UTC, fashxp commented on bundles/AdminBundle/Resources/public/js/pimcore/object/classes/layout/text.js
> +                                    html: 'You can use the following markup (in source edit mode) to make custom alerts: <br> <pre>&lt;div class=&quot;alert alert-success&quot;&gt;Your Message&lt;/di
should we add a info for twig support here too?

2021-10-08 09:45 UTC, dvesh3 commented on bundles/AdminBundle/Controller/Admin/DataObject/ClassController.php
> +        $obj = DataObject::getByPath($objPath) ?? new DataObject\Concrete();
passing null when no object is provided to the `enrichLayoutDefinition`.

2021-10-08 09:45 UTC, dvesh3 commented on bundles/AdminBundle/Resources/public/js/pimcore/object/classes/layout/text.js
> +                                    html: 'You can use the following markup (in source edit mode) to make custom alerts: <br> <pre>&lt;div class=&quot;alert alert-success&quot;&gt;Your Message&lt;/di
Added

2021-10-08 09:50 UTC, fashxp commented on bundles/AdminBundle/Controller/Admin/DataObject/ClassController.php
> +        $obj = DataObject::getByPath($objPath) ?? new DataObject\Concrete();
does null solve the issue? then I would get a null error message. could we not just pass the class id to the request and then create an empty dataobject of correct type?

2021-10-11 07:53 UTC, dvesh3 commented on bundles/AdminBundle/Controller/Admin/DataObject/ClassController.php
> +        $obj = DataObject::getByPath($objPath) ?? new DataObject\Concrete();
Changed it to use default class object when none is provided in the field.

2021-10-13 07:57 UTC, merged