Add advanced menu items for expand collapse all
pimcore/pimcore pull request #10521
Opened 2021-10-06 19:16 UTC by matthiashamacher

## Changes in this pull request  
Resolves #9928

2021-10-07 13:11 UTC, brusch requested changes
Please see my inline comments on the code. 
Please also remove all translations except the one for `en`. Translations are managed here: https://poeditor.com/join/project/VWmZyvFVMH

Thanks!

2021-10-07 13:11 UTC, brusch commented on bundles/AdminBundle/Resources/public/js/pimcore/object/tree.js
> +            if (record.data.type === "folder") {
```suggestion
            if (!record.data.leaf) {
```
Also objects and variants can have children.

2021-10-07 13:11 UTC, brusch commented on bundles/AdminBundle/Resources/public/js/pimcore/document/tree.js
> +            if (record.data.type === "folder") {
```suggestion
            if (!record.data.leaf) {
```
Also pages can have children 😉

2021-10-07 13:11 UTC, brusch commented on bundles/AdminBundle/Resources/public/js/pimcore/asset/tree.js
> +            if (record.data.type === "folder") {
```suggestion
            if (!record.data.leaf) {
```

2021-10-07 16:36 UTC, matthiashamacher commented
I've implemented your requested changes.

2021-10-12 07:32 UTC, brusch commented
Nice, thanks a lot! 👍

2021-10-12 07:32 UTC, merged