[Admin] Grids - Replace cellEditing with RowEditing
pimcore/pimcore pull request #10646
Opened 2021-10-19 08:01 UTC by dvesh3

## Changes in this pull request  
In Admin interface, adding and updating settings on grids is cumbersome with cell-editing plugin as each cell edit fires an update request, which sometimes breaks when multiple requests are fired in close intervals, so I would like to propose using RowEditing instead of CellEditing plugin.

With Row Editing plugin, only one request is fired when clicking on update or pressing Enter. 
![image](https://user-images.githubusercontent.com/5137917/137859929-354734ce-701c-4eee-9b0f-c1dc11dc2be2.png)

Grids covered:
 - Glossary
 - Unit settings
 - Document Types
 - Predefined Properties
 - Static Routes
 - Translations
 - Website Settings
 - Redirects

2021-10-19 10:04 UTC, dvesh3 commented
@fashxp @brusch what do you guys think about this change?

2021-10-20 07:04 UTC, brusch commented
Works like a charm - just one thing - could we maybe stop the row-editor from opening if the row isn't writable? Then it would be super smooth 😊
![image](https://user-images.githubusercontent.com/142037/138044047-9775d4c0-95b8-4f49-ab48-dae37536f8b1.png)

2021-10-20 07:48 UTC, dvesh3 commented
> Works like a charm - just one thing - could we maybe stop the row-editor from opening if the row isn't writable? Then it would be super smooth 😊 ![image](https://user-images.githubusercontent.com/142037/138044047-9775d4c0-95b8-4f49-ab48-dae37536f8b1.png)

@brusch yes, that's possible with `beforeedit` event listener like:
```js
beforeedit: function (editor, context, eOpts) {
    if (!context.record.data.writeable) {
        return false;
    }
}
```

2021-10-21 07:05 UTC, brusch commented
@dvesh3 nice, then I'd go for it 👍

2021-10-21 08:45 UTC, matthiashamacher commented on bundles/AdminBundle/Resources/public/js/pimcore/settings/translations.js
> +                    for (var i=0; i < cm.length; i++) {
As you use `let` already for the other variables, you could use it here too instead of `var` so it is consistent.

2021-10-21 08:45 UTC, matthiashamacher commented on bundles/AdminBundle/Resources/public/js/pimcore/settings/website.js
> +                    for (var i=0; i < cm.length; i++) {
Same here, please use `let`

2021-11-16 14:06 UTC, brusch commented
@dvesh3 Looks good to me, just one thing, the quantity value grid doesn't save any values, can you please fix that 😊 Thanks a lot!

2021-11-16 14:07 UTC, brusch requested changes
@dvesh3 Looks good to me, just one thing, the quantity value grid doesn't save any values, can you please fix that 😊 Thanks a lot!

2021-11-17 15:43 UTC, dvesh3 commented
> @dvesh3 Looks good to me, just one thing, the quantity value grid doesn't save any values, can you please fix that 😊 Thanks a lot!

@brusch Fixed.

2021-11-18 08:21 UTC, merged