[Documents] Blocks Editable - Ignore adding extra indices on required check and xliff export
pimcore/pimcore pull request #10652
Opened 2021-10-19 14:11 UTC by dvesh3

## Changes in this pull request  
Resolves #10443

## Additional info

2021-10-19 14:39 UTC, brusch requested changes

2021-10-19 14:39 UTC, brusch commented on models/Document/Editable/Block.php
> +        return $requestStack->getCurrentRequest()->get(self::IGNORE_EDITMODE_INDICES, false);
Just to be sure, I'd add a check here if `getCurrentRequest() !== null` .

2021-10-19 15:14 UTC, dvesh3 commented on models/Document/Editable/Block.php
> +        return $requestStack->getCurrentRequest()->get(self::IGNORE_EDITMODE_INDICES, false);
Returning `false` on `getCurrentRequest() === null`

2021-10-20 07:49 UTC, brusch approved these changes

2021-10-20 07:54 UTC, merged