add info that %Text( paramname) deprecated
pimcore/pimcore pull request #10728
Opened 2021-10-28 17:08 UTC by frithjof

## Changes in this pull request  
Resolves #

## Additional info

2021-10-29 06:35 UTC, blankse commented on doc/Development_Documentation/19_Development_Tools_and_Details/25_Email_Framework/README.md
> +```php
```suggestion
```twig
```

2021-10-29 09:34 UTC, brusch requested changes

2021-10-29 09:34 UTC, brusch commented on doc/Development_Documentation/19_Development_Tools_and_Details/25_Email_Framework/README.md
> +you can access the parameters in your mail content now in standard twig syntax instead of the old %Text(paramname);
```suggestion
you can access the parameters in your mail content in standard twig syntax.
```
Since this is the current documentation, we don't need to mention the old (and removed) syntax here.

2021-10-29 10:16 UTC, frithjof commented on doc/Development_Documentation/19_Development_Tools_and_Details/25_Email_Framework/README.md
> +you can access the parameters in your mail content now in standard twig syntax instead of the old %Text(paramname);
I would mention it because it is still in the image above used

2021-10-29 11:58 UTC, brusch commented on doc/Development_Documentation/19_Development_Tools_and_Details/25_Email_Framework/README.md
> +you can access the parameters in your mail content now in standard twig syntax instead of the old %Text(paramname);
I think we should then update the image as well. Doesn't make sense to have that still in the image if it doesn't work anymore 😊

2021-10-30 09:48 UTC, frithjof commented
image is now updated too and added example for using an Object

2021-11-03 13:16 UTC, brusch commented
Very nice, thanks a lot! 👍

2021-11-03 13:16 UTC, merged