FIX(10600): update object_url_slug to correct character set and collate
pimcore/pimcore pull request #10723
Opened 2021-10-28 14:00 UTC by BabovicT

Resolves #10600

2021-10-29 07:26 UTC, dvesh3 commented on bundles/CoreBundle/Migrations/Version20211028155535.php
> +final class Version20211028134037 extends AbstractMigration
```suggestion
final class Version20211028155535 extends AbstractMigration
```

2021-10-29 07:26 UTC, dvesh3 commented on bundles/InstallBundle/Resources/install.sql
> +      `slug` varchar(765) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL, /* slug in utf8 (3-byte) using the full key length of 3072 bytes */
Comment should be changed as well.

2021-10-29 07:51 UTC, BabovicT commented on bundles/InstallBundle/Resources/install.sql
> +      `slug` varchar(765) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL, /* slug in utf8 (3-byte) using the full key length of 3072 bytes */
like that?

2021-10-29 07:58 UTC, dvesh3 commented on bundles/InstallBundle/Resources/install.sql
> +      `slug` varchar(765) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL, /* slug in utf8 (3-byte) using the full key length of 3072 bytes */
Also the charset to `utf8mb4`. thanks!

2021-10-29 08:13 UTC, BabovicT commented on bundles/InstallBundle/Resources/install.sql
> +      `slug` varchar(765) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL, /* slug in utf8 (3-byte) using the full key length of 3072 bytes */
There. Sry about that.

2021-10-29 09:24 UTC, brusch requested changes

2021-10-29 09:24 UTC, brusch commented on bundles/InstallBundle/Resources/install.sql
> +      `slug` varchar(765) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL, /* slug in utf8mb4 (4-byte) using the full key length of 4096 bytes */
```suggestion
      `slug` varchar(765) NOT NULL, /* slug in utf8mb4 (4-byte) using the full key length of 3072 bytes */
```
We can omit setting the charset and collation here, as it is the default anyway. Also the max key length doesn't change, it's a MySQL limitation.

2021-11-03 13:20 UTC, merged

2021-11-03 13:20 UTC, brusch commented
Thanks a lot! 👍