Fix data load for user with id 0
pimcore/pimcore pull request #10783
Opened 2021-11-08 11:30 UTC by mhgtlc

Fix null data for user with id 0, `\Pimcore\Model\User::getById(0);` now returns null

2021-11-08 11:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/pimcore/pimcore?pullRequest=10783) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/pimcore/pimcore?pullRequest=10783) before we can accept your contribution.<br/><hr/>**Mihail Gutuleac** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/pimcore/pimcore?pullRequest=10783) it.</sub>

2021-11-08 12:34 UTC, brusch requested changes
Just a simple `if` should be sufficient 😉

2021-11-08 12:34 UTC, brusch commented on models/User/AbstractUser/Dao.php
> +        if (!empty($data)) {
```suggestion
        if ($data) {
```

2021-11-08 12:34 UTC, brusch commented on models/User/AbstractUser/Dao.php
> +        if (!empty($data)) {
```suggestion
        if ($data) {
```

2021-11-08 13:34 UTC, mhgtlc commented on models/User/AbstractUser/Dao.php
> +        if (!empty($data)) {
Fixed

2021-11-08 14:06 UTC, brusch commented
@mhgtlc could you please also sign the CLA? Thanks again!

2021-11-08 14:50 UTC, brusch commented
@mhgtlc please see also the instructions above, you have to ensure the email address used for the Git commit is also mapped in your GitHub settings. 
https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user

You can check the used email address in the patch file: 
https://patch-diff.githubusercontent.com/raw/pimcore/pimcore/pull/10783.patch

it's located in the second line.

2021-11-08 15:14 UTC, mhgtlc commented
> https://patch-diff.githubusercontent.com/raw/pimcore/pimcore/pull/10783.patch

Fixed, can you please check once again? Thank you

2021-11-10 09:25 UTC, brusch approved these changes

2021-11-10 09:54 UTC, merged

2021-11-10 09:54 UTC, brusch commented
Thank you! 👍