Show Public URL for documents in backend
pimcore/pimcore pull request #10837
Opened 2021-11-15 10:24 UTC by jelena-hrga

Resolves #10832
Added public URL and pretty URL on document info popup

2021-11-15 10:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/pimcore/pimcore?pullRequest=10837) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/pimcore/pimcore?pullRequest=10837) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/pimcore/pimcore?pullRequest=10837) it.</sub>

2021-11-15 11:17 UTC, brusch commented
Thanks for your PR! 
I think we should have just one field für the public URL. If there's a pretty URL, this should be used, if not, the path of the document. I think we'd need to fix this here: https://github.com/pimcore/pimcore/blob/36a44b071f98d6e632312e6e797006ef4af20f94/models/Document/PageSnippet.php#L600

Can you please change your PR accordingly? 
Thanks a lot!

2021-11-15 13:45 UTC, jelena-hrga commented
@brusch Thank you for the feedback, I changed my PR accordingly.

2021-11-16 14:17 UTC, brusch requested changes

2021-11-16 14:17 UTC, brusch commented on models/Document/PageSnippet.php
> +        $url .= $this->getPrettyUrl() ?: $this->getFullPath();
```suggestion
        if($this instanceof Page && $this->getPrettyUrl()) {
            $url .= $this->getPrettyUrl();
        } else {
            $url .= $this->getFullPath();
        }
```

2021-11-16 14:18 UTC, brusch commented on models/Document/PageSnippet.php
> +        $url .= $this->getPrettyUrl() ?: $this->getFullPath();
We need to check if `$this` is a `Page` because `Snippet` doesn't have the method `getPrettyUrl()`.

2021-11-16 14:24 UTC, merged

2021-11-16 14:24 UTC, brusch commented
Thank you very much!