Bugfix: add UTF-8 support to Input regex validation
pimcore/pimcore pull request #11033
Opened 2021-12-15 15:49 UTC by r-vanstraaten

Regex validation in dataobjects currently does not support UTF-8, making unicode regex validation impossible.
Added 'u' modifier to checkValidity method to resolve.

Steps to reproduce:

- Add regex validation to Dataobject field with Unicode (Example "a-zA-Z\x{00C0}\-\x{024F}0-9" to support diacritics)
- Attempting to save object should result in the following exception: Exception: ErrorException: Warning: preg_match(): Compilation failed: character code point value in \x{} or \o{} is too large

  
  

## Changes in this pull request  
Resolves #

## Additional info

2021-12-15 15:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/pimcore/pimcore?pullRequest=11033) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/pimcore/pimcore?pullRequest=11033) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/pimcore/pimcore?pullRequest=11033) it.</sub>

2021-12-15 15:52 UTC, dvesh3 commented
@r-vanstraaten thanks for your PR! since this is a bugfix, please rebase it on branch 10.2.

2021-12-15 16:28 UTC, r-vanstraaten commented
@dvesh3 I believe that should have fixed it, apologies for the incorrect branch initially!

2021-12-16 13:42 UTC, dvesh3 requested changes, later dismissed
Please add unicode flag to input.js:
https://github.com/DivanteLtd/pimcore/blob/93d49b761457c8016047d6506dfa45e91974610a/bundles/AdminBundle/Resources/public/js/pimcore/object/tags/input.js#L99

https://github.com/pimcore/pimcore/blob/2f18a0f26380c56b609d937b40d2050c8d1a3e1a/bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/input.js#L116

 otherwise it will highlight the field with validation message even when the value is correct.

2021-12-17 09:51 UTC, r-vanstraaten commented
@dvesh3 
Are you sure? I've tested it locally myself and asked a colleague to check, neither of us are getting validation errors/highlights/flashes. Tested with save without publish and direct save & publish, I've been unable to reproduce any validation messages
Screenshots of a test field below:
![image](https://user-images.githubusercontent.com/60101908/146525098-10fb9767-4aa9-4232-a56a-09a4eed43f74.png)
![image](https://user-images.githubusercontent.com/60101908/146525141-2af7ccb9-5a8f-4eb5-bec4-a9bbcdbea1fb.png)
![image](https://user-images.githubusercontent.com/60101908/146525188-2bd8c335-344d-4b73-a213-9c8ea2e2fb4a.png)

2021-12-17 10:07 UTC, merged

2021-12-17 10:07 UTC, dvesh3 commented
@r-vanstraaten thanks!