[Assets] Add normalize/denormalize method for metadata
pimcore/pimcore pull request #11596
Opened 2022-03-04 16:52 UTC by dvesh3

## Changes in this pull request  
Resolves #8489

## Additional info

2022-03-07 15:46 UTC, blankse commented on models/Asset/MetaData/ClassDefinition/Data/Asset.php
> +     * @deprecated use normalize() instead, will be removed in Pimcore 11
We should add trigger_deprecation() in method body

2022-03-07 17:07 UTC, dvesh3 commented on models/Asset/MetaData/ClassDefinition/Data/Asset.php
> +     * @deprecated use normalize() instead, will be removed in Pimcore 11
Good catch! done 😉

2022-03-23 15:55 UTC, fashxp requested changes
the data retrieved via getter and after a normalize-denormalize cascade should be the same. 

is not the case for metadata of type `asset`, `document` and `object`

we should also add a test for that  ... snippet for a headstart of that test could be as follows: 

```php 
        $loader = \Pimcore::getContainer()->get('pimcore.implementation_loader.asset.metadata.data');
        
        $asset = Asset::getById(68);
        $metadataList = $asset->getMetadata();

        foreach($metadataList as $metaData) {
            try {
                /** @var Data $instance */
                $instance = $loader->build($metaData['type']);

                $marshalledData = $instance->normalize($metaData['data']);
                $unmarshalledData = $instance->denormalize($marshalledData);

                p_r($metaData['name'] . ': ');
                p_r($unmarshalledData === $metaData['data']);
                p_r("-------------------");

            } catch (UnsupportedException $e) {
            }


        }
```

2022-03-23 15:55 UTC, fashxp commented on models/Asset/Service.php
> +use Pimcore\Normalizer\NormalizerInterface;
why do we need that import here?

2022-03-24 14:37 UTC, dvesh3 commented on models/Asset/Service.php
> +use Pimcore\Normalizer\NormalizerInterface;
yes, we can get rid of it,

2022-03-29 10:22 UTC, fashxp approved these changes

2022-04-04 11:45 UTC, merged