[Application logger] Correct log file object path if PIMCORE_PROJECT_ROOT is /app
pimcore/pimcore pull request #11601
Opened 2022-03-07 07:41 UTC by BlackbitNeueMedien

Follow-up of #11555 
In the other PR we forgot this place.

2022-03-07 14:01 UTC, brusch requested changes

2022-03-07 14:01 UTC, brusch commented on lib/Log/ApplicationLogger.php
>              } else {
Should we maybe add an `instanceof` here?

2022-03-07 15:39 UTC, BlackbitNeueMedien commented on lib/Log/ApplicationLogger.php
>              } else {
In this `is_string` case? Or do you mean https://github.com/pimcore/pimcore/pull/11601/files#diff-935282905cd71faeda62809e162086e37f92682e8f041d8e6e40eafe55f2c11cR155

2022-03-07 16:16 UTC, brusch commented on lib/Log/ApplicationLogger.php
>              } else {
Yeah, I mean changing the `else` to an `elseif($context['fileObject'] instanceof FileObject)`.

2022-03-07 18:25 UTC, BlackbitNeueMedien commented on lib/Log/ApplicationLogger.php
>              } else {
Fixed

2022-03-08 09:57 UTC, merged

2022-03-08 09:57 UTC, brusch commented
Nice, thanks a lot! 👍