Image Optimization using the new package - spatie/image-optimizer
pimcore/pimcore pull request #11763
Opened 2022-03-25 15:24 UTC by aryaantony92

## Changes in this pull request  
Resolves #

## Additional info

2022-03-29 13:08 UTC, brusch requested changes

2022-03-29 13:08 UTC, brusch commented on bundles/CoreBundle/Resources/config/image_optimizers.yaml
> +#    Pimcore\Image\Optimizer\AdvancedPngOptimizer:
```suggestion
#    Pimcore\Image\Optimizer\AdvancedPngOptimizer:
```
We should keep the service definitions for compatibility reasons, we just remove the tags configuration.

2022-03-29 15:25 UTC, dvesh3 commented on composer.json
> +    "spatie/image-optimizer": "1.6.2"
```suggestion
    "spatie/image-optimizer": "^1.6.2"
```

2022-03-30 08:17 UTC, jdreesen commented on doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
> +- [Spatie/image-optimizer instead of custom] Custom image optimizer (for thumbnail images) is deprecated and a new image optimizer Spatie/image optimizer is introduced.
This sentence is somehow broken...

2022-03-30 08:17 UTC, jdreesen commented on lib/Image/Optimizer/AbstractCommandOptimizer.php
> +**/
```suggestion
/**
 * @deprecated since 10.4 version and will be removed in Pimcore 11. use the Spatie Image Optimizer instead
 */
```

2022-04-01 12:14 UTC, brusch commented
@aryaantony92 we should also update the requirements check here: 
https://github.com/pimcore/pimcore/blob/7290a06a18b9ee559b7442dc174948b95a048f12/lib/Tool/Requirements.php#L422 
and the docs as well: 
https://github.com/pimcore/pimcore/blob/173a1f2c09619767d66413b907282c8db9fd865a/doc/Development_Documentation/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/06_Additional_Tools_Installation.md#L47
https://github.com/pimcore/pimcore/blob/d9f360b8e277d7d2c870b485b4f01408ae138394/doc/Development_Documentation/23_Installation_and_Upgrade/01_System_Requirements.md#L107

2022-04-01 12:18 UTC, brusch commented on doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
> +- [Image Optimizer] Image Optimizer services (e.g. PngCrushOptimizer, JpegoptimOptimizer etc.) are deprecated and will be
We should also mention that the existing optimizers were disabled by default and we should also describe here how to re-enable them again if necessary.

2022-04-04 13:02 UTC, brusch commented
@aryaantony92 see todo's from above 😉 

- [ ] https://github.com/pimcore/pimcore/pull/11763#issuecomment-1085824528
- [ ] https://github.com/pimcore/pimcore/pull/11763#discussion_r840528364

2022-04-04 17:14 UTC, jdreesen commented on doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
> +  Currently, the existing optimizers are disabled and if you still want to use them, then please re-enable it as follows. In the image_optimizers.yaml file, add the tag " { name: pimcore.image.optimi
```suggestion
  Currently, the existing optimizers are disabled. If you still want to use them, then please re-enable them as follows: in the `image_optimizers.yaml` file, add the tag `{ name: pimcore.image.optimizer }` under the required service definitions. For example: if you want to re-enable the `CjpegOptimizer`, you can add the tag `{ name: pimcore.image.optimizer }` under the service definition of `CjpegOptimizer` (which is: `Pimcore\Image\Optimizer\JpegoptimOptimizer`).
```

2022-04-05 09:49 UTC, brusch commented on doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
> +  Currently, the existing optimizers are disabled. If you still want to use them, then please re-enable them as follows: in the `image_optimizers.yaml` file, add the tag `{ name: pimcore.image.optimi
```suggestion
  Currently, the existing optimizers are disabled. If you still want to use them, then please re-enable them by tagging the services accordingly (in your `services.yaml`):
  
```yaml
    Pimcore\Image\Optimizer\CjpegOptimizer:
        tags:
            - { name: pimcore.image.optimizer }

    Pimcore\Image\Optimizer\JpegoptimOptimizer:
        tags:
            - { name: pimcore.image.optimizer }

    Pimcore\Image\Optimizer\PngCrushOptimizer:
        tags:
            - { name: pimcore.image.optimizer }
            
```
```

2022-04-05 10:02 UTC, brusch approved these changes

2022-04-05 10:03 UTC, merged