Fix deprecation in Numeric
pimcore/pimcore pull request #11787
Opened 2022-03-28 15:20 UTC by dpfaffenbauer

2022-03-28 15:59 UTC, jdreesen commented on models/DataObject/ClassDefinition/Data/Numeric.php
> +        return empty($data) || strlen($data) < 1;
Not sure if this is right, as `"0"` is considered empty (see: https://3v4l.org/mgSdd).

2022-03-28 18:09 UTC, dpfaffenbauer commented on models/DataObject/ClassDefinition/Data/Numeric.php
> +        return empty($data) || strlen($data) < 1;
true, lets wait on how we resolve that on the other PR

2022-03-29 06:43 UTC, dpfaffenbauer commented on models/DataObject/ClassDefinition/Data/Numeric.php
> +        return empty($data) || strlen($data) < 1;
I think we should check if $data is actually a number, if not it is invalid.

2022-03-29 08:31 UTC, brusch requested changes

2022-03-29 08:31 UTC, brusch commented on models/DataObject/ClassDefinition/Data/Numeric.php
> +        return empty($data) || strlen($data) < 1;
```suggestion
        return is_numeric($data);
```
This should do the trick in this case.

2022-03-29 08:32 UTC, brusch commented on models/DataObject/ClassDefinition/Data/Numeric.php
> +        return is_numeric($data);
```suggestion
        return !is_numeric($data);
```

2022-03-29 08:40 UTC, merged

2022-03-29 08:42 UTC, dpfaffenbauer commented
thanks @brusch