fix: PHP 8.1 doesn't allow passing null to explode()
pimcore/pimcore pull request #11780
Opened 2022-03-28 13:58 UTC by dkarlovi

## Additional info  

When on PHP 8.1, this produces a deprecation:
```
Deprecated: explode(): Passing null to parameter #2 ($string) of type string is deprecated
```

2022-03-28 14:07 UTC, brusch requested changes

2022-03-28 14:07 UTC, brusch commented on models/Staticroute.php
> +        if ($array === null) {
```suggestion
        if (empty($array)) {
```
Using `empty()` would cover empty strings as well.

2022-03-28 14:19 UTC, dkarlovi commented on models/Staticroute.php
> +        if ($array === null) {
I don't really use `empty` because it's too lenient (exactly how you show), one exception is checking for property initializations. Accepted your suggestion. :+1:

2022-03-28 16:12 UTC, jdreesen commented on models/Staticroute.php
> +        $array = $this->getDefaults();
`$array` is a bit strange as a variable name, considering that the return type of `getDefaults()` is `string`.

2022-03-28 17:04 UTC, dkarlovi commented on models/Staticroute.php
> +        $array = $this->getDefaults();
@jdreesen good point!

2022-03-29 07:13 UTC, brusch requested changes

2022-03-29 07:13 UTC, brusch commented on models/Staticroute.php
> +        $array = $this->getDefaults();
```suggestion
        $defaultsString = $this->getDefaults();
```

2022-03-29 07:13 UTC, brusch commented on models/Staticroute.php
> +        if (empty($array)) {
```suggestion
        if (empty($defaultsString)) {
```

2022-03-29 07:13 UTC, brusch commented on models/Staticroute.php
> +        $t = explode('|', $array);
```suggestion
        $t = explode('|', $defaultsString);
```

2022-03-29 07:14 UTC, brusch commented on models/Staticroute.php
> +        $array = $this->getDefaults();
@jdreesen valid point, renamed it, thanks 🙃

2022-03-29 08:51 UTC, merged

2022-03-29 08:51 UTC, brusch commented
Thanks!