Change sort method permission
pimcore/pimcore pull request #11910
Opened 2022-04-14 09:10 UTC by andi-schlosser

## Changes in this pull request  
Resolves #11716

## Additional info  

A backend user with the new permission `objects_sort_method` is now able to change the sorting method (key or index) of children of data objects without needing to be a full admin.

2022-04-14 09:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/pimcore/pimcore?pullRequest=11910) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/pimcore/pimcore?pullRequest=11910) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/pimcore/pimcore?pullRequest=11910) it.</sub>

2022-04-25 14:08 UTC, fashxp requested changes
thx very much, looks good to me. 
could you please remove the german translation.

2022-04-25 14:08 UTC, fashxp commented on bundles/CoreBundle/Resources/translations/de.json
> +    "objects_sort_method": "Sortiermethode für Data Objects ändern"
please only provide english translations. all other translations are provided via POeditor.

2022-04-26 09:43 UTC, andi-schlosser commented on bundles/CoreBundle/Resources/translations/de.json
> +    "objects_sort_method": "Sortiermethode für Data Objects ändern"
Thank you for your feedback. I removed the german translation.

2022-04-26 09:52 UTC, fashxp approved these changes

2022-04-26 10:10 UTC, merged