[DataObject] Grid column config pre send data event
pimcore/pimcore pull request #12029
Opened 2022-05-04 14:47 UTC by kjkooistra-youwe

Allow modifying the grid column configuration before it is sent by dispatching
an admin event similar to the object pre send data event.

2022-05-05 09:08 UTC, kingjia90 commented
Thank you for the PR! 
Could you please merge the current branch into this PR? The problems (unrelated to this PR) causing the PHPStan to fail just got fixed.

2022-05-19 10:21 UTC, aryaantony92 requested changes

2022-05-19 10:21 UTC, aryaantony92 commented on bundles/AdminBundle/Controller/Admin/DataObject/DataObjectHelperController.php
>       *
* @param EventDispatcherInterface $eventDispatcher

2022-05-19 10:21 UTC, aryaantony92 commented on bundles/AdminBundle/Controller/Admin/DataObject/DataObjectHelperController.php
>       *
@param EventDispatcherInterface $eventDispatcher

2022-05-19 10:24 UTC, aryaantony92 requested changes

2022-05-19 10:24 UTC, aryaantony92 commented on bundles/AdminBundle/Controller/Admin/DataObject/DataObjectHelperController.php
>       *
* @param EventDispatcherInterface $eventDispatcher

2022-05-19 10:24 UTC, aryaantony92 commented on bundles/AdminBundle/Controller/Admin/DataObject/DataObjectHelperController.php
>       *
* @param EventDispatcherInterface $eventDispatcher

2022-05-19 10:26 UTC, aryaantony92 commented
@kjkooistra-youwe Could you please add the "EventDispatcherInterface $eventDispatcher" Param also before the method calls

2022-05-19 11:33 UTC, merged

2022-05-19 11:42 UTC, aryaantony92 commented
@kjkooistra-youwe Thank you.