Removed `o_` prefix from `o_properties` property
pimcore/pimcore pull request #12080
Opened 2022-05-10 09:41 UTC by aashan10

WIP: Migrating properties with `o_` prefix to the properties with removed prefixes

2022-05-10 10:00 UTC, brusch requested changes
Of course we also need to consider `Asset`  and `Document`. 😊

2022-05-10 10:00 UTC, brusch commented on models/DataObject/AbstractObject.php
> +        $this->o_properties = & $this->properties;
@aashan10 as `o_properties` is tagged as `@internal` we don't need this BC layer here and we can just remove the property.

2022-05-10 10:05 UTC, brusch commented on models/DataObject/AbstractObject.php
> +        $this->o_properties = & $this->properties;
additionally we need to consider this change in `_sleep()` and `wakeup()`.

2022-05-10 10:23 UTC, aashan10 commented on models/DataObject/AbstractObject.php
> +        $this->o_properties = & $this->properties;
@brusch I didn't see `o_properties` being used by `Asset` and `Document` classes so I don't know if anything needs to be changed there.

Also, I have updated the `__sleep` and `__wakeup` methods.

2022-05-10 11:59 UTC, brusch commented on models/DataObject/AbstractObject.php
> +        $this->o_properties = & $this->properties;
@aashan10 there, they are not prefixed 😉 The `o_` prefix was only on data objects for historical reasons, but actually most of them also exist in `Asset` and `Document` without the prefix, but the same purpose. 

See e.g.: 
https://github.com/pimcore/pimcore/blob/d05c900e6e40273ac80c345ef74b9a3c812de91a/models/Asset.php#L1413
https://github.com/pimcore/pimcore/blob/430706e64baa0b42112541a4379f63387061d0c2/models/Document.php#L1254

They share exactly the same code, that can be unified into `ElementAbstract`. 
Things like the cache tag, can be solved by e.g. using `Element\Service::getElementType()`.

2022-05-10 12:18 UTC, aashan10 commented on models/DataObject/AbstractObject.php
> +        $this->o_properties = & $this->properties;
Ahh .. got it. Thanks. I'm having better understanding now. I'll have to remove these duplicate methods in Asset and Document as well. Got it!

2022-05-12 08:36 UTC, brusch requested changes

2022-05-12 08:36 UTC, brusch commented on models/Element/AbstractElement.php
> +        $property->setCtype('object');
```suggestion
        $property->setCtype(Service::getElementType($this));
```

2022-05-12 08:49 UTC, merged