[TASK] improve delete message for tags/fieldcollections/objectbricks/…
pimcore/pimcore pull request #12102
Opened 2022-05-12 06:46 UTC by dpfahlbusch

…users and add confirmdialog to thumbnails/customreports

## Changes in this pull request  
Partly Resolves #6259

## Additional info

2022-05-12 06:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/pimcore/pimcore?pullRequest=12102) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/pimcore/pimcore?pullRequest=12102) before we can accept your contribution.<br/><hr/>**Dennis Pfahlbusch** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/pimcore/pimcore?pullRequest=12102) it.</sub>

2022-05-12 09:54 UTC, dpfahlbusch commented
@brusch should be ready for review :)

2022-05-12 10:11 UTC, blankse commented
Wouldn't it be better to just create one translation with 2 parameters?

2022-05-12 11:29 UTC, blankse commented
Can you use the translation function for the type parameter. So this can also be translated.

2022-05-12 12:19 UTC, blankse approved these changes
LGTM, thank you 👍🏼

2022-05-12 12:34 UTC, dpfahlbusch commented
Just added a minor change, because i was working on the menus:
changed the icon of delete fieldcollection (was in an earlier commit today) and delete objectbrick to make it consistent with delete class :)

2022-05-25 08:41 UTC, aryaantony92 commented on bundles/AdminBundle/Resources/public/js/pimcore/object/classificationstore/collectionsPanel.js
> +                        Ext.Msg.confirm(t('delete'), sprintf(t('delete_message_advanced'), t('classificationstore_collection'), data.data.text), function(btn) {
Ext.Msg.confirm(t('delete'), sprintf(t('delete_message_advanced'), t('classificationstore_collection'), data.data.text), function(btn) {

2022-05-25 08:46 UTC, aryaantony92 requested changes

2022-05-25 08:46 UTC, aryaantony92 commented on bundles/AdminBundle/Resources/public/js/pimcore/object/classificationstore/collectionsPanel.js
> +                        Ext.Msg.confirm(t('delete'), sprintf(t('delete_message_advanced'), t('classificationstore_collection'), data.data.text), function(btn) {
```suggestion
                        Ext.Msg.confirm(t('delete'), sprintf(t('delete_message_advanced'), t('classificationstore_collection'), data.data.name), function(btn) {
```

2022-05-25 08:46 UTC, aryaantony92 commented on bundles/AdminBundle/Resources/public/js/pimcore/object/classificationstore/groupsPanel.js
> +                        Ext.Msg.confirm(t('delete'), sprintf(t('delete_message_advanced'), t('classificationstore_relation'), data.data.text), function(btn) {
```suggestion
                        Ext.Msg.confirm(t('delete'), sprintf(t('delete_message_advanced'), t('classificationstore_relation'), data.data.keyName), function(btn) {
```

2022-05-25 08:46 UTC, aryaantony92 commented on bundles/AdminBundle/Resources/public/js/pimcore/object/classificationstore/groupsPanel.js
> +                        Ext.Msg.confirm(t('delete'), sprintf(t('delete_message_advanced'), t('classificationstore_group'), data.data.text), function(btn) {
```suggestion
                        Ext.Msg.confirm(t('delete'), sprintf(t('delete_message_advanced'), t('classificationstore_group'), data.data.name), function(btn) {
```

2022-05-25 08:46 UTC, aryaantony92 commented on bundles/AdminBundle/Resources/public/js/pimcore/settings/staticroutes.js
> +                        Ext.Msg.confirm(t('delete'), sprintf(t('delete_message_advanced'), t('staticroute'), data.data.text), function (btn) {
```suggestion
                        Ext.Msg.confirm(t('delete'), sprintf(t('delete_message_advanced'), t('staticroute'), data.data.name), function (btn) {
```

2022-05-25 08:52 UTC, aryaantony92 requested changes

2022-05-25 08:52 UTC, aryaantony92 commented on bundles/AdminBundle/Resources/public/js/pimcore/object/classificationstore/propertiesPanel.js
> +                        Ext.Msg.confirm(t('delete'), sprintf(t('delete_message_advanced'), t('classificationstore_property'), data.data.text), function(btn) {
```suggestion
                        Ext.Msg.confirm(t('delete'), sprintf(t('delete_message_advanced'), t('classificationstore_property'), data.data.name), function(btn) {
```

2022-05-25 09:58 UTC, aryaantony92 commented on bundles/AdminBundle/Resources/public/js/pimcore/object/classificationstore/collectionsPanel.js
> +                        Ext.Msg.confirm(t('delete'), sprintf(t('delete_message_advanced'), t('classificationstore_collection_relation'), data.data.text), function(btn) {
```suggestion
                        Ext.Msg.confirm(t('delete'), sprintf(t('delete_message_advanced'), t('classificationstore_collection_relation'), data.data.groupName), function(btn) {
```

2022-05-25 11:55 UTC, aryaantony92 requested changes

2022-05-25 11:55 UTC, aryaantony92 commented on bundles/AdminBundle/Resources/public/js/pimcore/settings/targeting/rules/panel.js
>          });
```suggestion
       }.bind(this));
```

2022-05-25 11:55 UTC, aryaantony92 commented on bundles/AdminBundle/Resources/public/js/pimcore/settings/targeting/targetGroups/panel.js
>          });
```suggestion
      }.bind(this));
```

2022-05-25 12:06 UTC, aryaantony92 approved these changes

2022-05-25 12:06 UTC, merged

2022-05-25 12:09 UTC, aryaantony92 commented
@dpfahlbusch Thank you