[Db] remove all usages of Pimcore\Db\ConnectionInterface and Pimcore\Db\PimcoreExtensionstrait
pimcore/pimcore pull request #12123
Opened 2022-05-16 06:24 UTC by dpfaffenbauer

Version 2 of https://github.com/pimcore/pimcore/pull/10653

2022-05-30 12:06 UTC, brusch commented
@dpfaffenbauer have you seen the issues reported by PhpStan?

2022-06-07 06:46 UTC, dpfaffenbauer commented
@brusch that is intentionally for now, have you seen my gitter message?

2022-06-08 08:49 UTC, brusch commented
@dpfaffenbauer 👍go ahead 😉

2022-06-08 09:03 UTC, brusch commented
So the approach is now to change the return types in `Pimcore\Db` first, so that we can then fix all issues (commit by commit) with the help of our lovely PhpStan. As soon as all issues are fixed, we change the return types back for compatibility.

2022-06-15 08:52 UTC, brusch commented
@dpfaffenbauer just a quick related info: @aashan10 will work on #12363 in the meantime - so that ones can be left out here. 

Another topic that came to my mind, how to deal with methods like `insertOrUpdate()` without making the application code more complex 🤔

2022-06-15 10:50 UTC, dpfaffenbauer commented
@brusch I had the inserOrUpdate in the old PR already done... With a Helper class basically.

2022-06-15 14:43 UTC, dpfaffenbauer commented
@brusch I think it would be good if @aashan10 makes changes in this PR, otherwise the merge could be quite difficult, what do you think?

2022-06-15 14:52 UTC, brusch commented
@dpfaffenbauer should be safe to do them in separate PRs and then after they got merged we merge 10.x back into this one. We need to keep the PRs easy to review, and as @aashan10 's tasks are fixing Doctrine deprecations  it's also not directly related to this PR 😉

2022-06-17 06:18 UTC, dpfaffenbauer commented
@brusch Changes made, tests are running. I'll revert the Db changes now to still return the Pimcore ConnectionInterface

2022-06-17 07:38 UTC, brusch requested changes

2022-06-17 07:38 UTC, brusch commented on bundles/CoreBundle/Migrations/Version20211103055110.php
> +        $classes = $db->fetchAssociative('SELECT id FROM classes');
That's unfortunalely not returning the same result. 
`fetchAssociative()` is equal to `fetchAll()` but `fetchRow()` is only returning the first row using indices.

2022-06-17 07:40 UTC, brusch commented
@dpfaffenbauer cool thanks! 
I think we now need to add the reported missing methods on `ConnectionInterface` as `@method` annotations to it, to get rid of the PhpStan errors, right?

2022-06-17 07:49 UTC, dpfaffenbauer commented
@brusch on it ;)

2022-06-17 08:02 UTC, dpfaffenbauer commented
@brusch, all done, tests are green :)

2022-06-21 08:17 UTC, aashan10 approved these changes

2022-06-23 08:19 UTC, brusch commented
Seems that PhpStorm needs the `@deprecated` on every single method on the interface and trait ... maybe because he gets confused because of the way it's defined ... anyway, I've added the annotations and it seems fine now 😊

2022-06-24 09:33 UTC, brusch requested changes

2022-06-24 09:33 UTC, brusch commented on lib/Db.php
>          $db = \Pimcore::getContainer()->get('database_connection');
```suggestion
        $db = \Pimcore::getContainer()->get('doctrine.dbal.default_connection');
```
We should use `doctrine.dbal.default_connection` here as well, to be consistent, right?

2022-06-24 09:33 UTC, brusch commented on lib/Db.php
>  use Pimcore\Db\Connection;
```suggestion
use Doctrine\DBAL\Connection;
```
Here we could use `Doctrine\DBAL\Connection` already, as it would be redundant by adding `ConnectionInterface` right?

2022-06-24 09:33 UTC, brusch commented on bundles/AdminBundle/EventListener/ImportConfigListener.php
> +        $importConfigIds = $db->fetchFirstColumn('select id from importconfigs where ownerId = ' . $userId);
```suggestion
        $importConfigIds = $db->fetchFirstColumn('select id from importconfigs where ownerId = ?', [$userId]);
```

2022-06-24 09:33 UTC, brusch commented on bundles/InstallBundle/Installer.php
>  use Pimcore\Db\Connection;
```suggestion
use Doctrine\DBAL\Connection;
```

2022-06-24 09:33 UTC, brusch commented on lib/Model/Listing/AbstractListing.php
```suggestion
```
This is obsolete 😊

2022-06-24 09:33 UTC, brusch commented on models/DataObject/AbstractObject/Dao.php
>              $permissions = $this->db->fetchAll($sql);
```suggestion
            $permissions = $this->db->fetchAllAssociative($sql);
```

2022-06-24 09:35 UTC, brusch commented
@dpfaffenbauer we are nearly there 😊 Please see my feedback & quickly resolve the conflicts. Thanks again!

2022-06-27 05:51 UTC, dpfaffenbauer commented on lib/Db.php
>  use Pimcore\Db\Connection;
ConnectionInterface does not have all the methods as Connection has. For BC reasons we need both here.

2022-06-27 06:23 UTC, dpfaffenbauer commented
@brusch all done

2022-06-27 07:57 UTC, brusch commented on lib/Db.php
>  use Pimcore\Db\Connection;
But shouldn't we include `Doctrine\DBAL\Connection` in the `@return` as well, as it has additional methods which are not covered by `Pimcore\Db\ConnectionInterface` and `Pimcore\Db\Connection` ?

2022-06-27 09:47 UTC, brusch commented on lib/Db.php
>  use Pimcore\Db\Connection;
@dpfaffenbauer have you noticed my above comment? 😊

2022-06-27 12:03 UTC, brusch commented
@dpfaffenbauer #12462 caused another conflict - may I ask you again - Sorry & Thanks ☺️

2022-06-27 12:48 UTC, dpfaffenbauer commented
@brusch done

2022-06-28 08:21 UTC, merged

2022-06-28 08:22 UTC, brusch commented
@dpfaffenbauer Thanks a lot - great work! 🙋

2022-06-28 08:28 UTC, dpfaffenbauer commented
💪

2022-06-28 08:48 UTC, brusch commented
Seems this is causing an issue now on install: 
```
Couldn't establish connection to MySQL: The given 'wrapperClass' Doctrine\DBAL\Connection has to be a subtype of \Doctrine\DBAL\Connection.
```

Just for reference. Needs further investigation.