addCondition default $value value should be array
pimcore/pimcore pull request #12562
Opened 2022-06-30 07:35 UTC by MercuryKojo

if you don't give a value for addCondition the function calls setParameters with [null] which gives an "SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens" Error
So the default value should be [], since setParameters requires array anyway

2022-07-01 07:11 UTC, brusch requested changes
Actually your change is a BC break, because the method signature changes and could break existing code. But my suggestion should fix the issue as well without breaking anything.

2022-07-01 07:11 UTC, brusch commented on bundles/EcommerceFrameworkBundle/OrderManager/Order/Listing.php
>          if (!is_array($value)) {
```suggestion
    public function addCondition($condition, $value = null)
    {
        if (null === $value) {
            $value = [];
        }
                
        if (!is_array($value)) {
```

2022-07-05 09:23 UTC, MercuryKojo commented
Yes makes sense.
Already accepted the change

2022-07-06 07:05 UTC, merged

2022-07-06 07:05 UTC, aryaantony92 commented
@MercuryKojo Thanks for the fix.