Deprecate Registering bundles through extensions.php
pimcore/pimcore pull request #12616
Opened 2022-07-08 15:36 UTC by dvesh3

## Changes in this pull request  
Resolves #12274

## Additional info

2022-07-18 09:11 UTC, brusch requested changes
I think a lot of methods in `\Pimcore\Extension\Bundle\PimcoreBundleManager` can be deprecated as well, such as `getActiveBundle()` or `enable()` and a lot more, right? 

`\Pimcore\Extension\Bundle\PimcoreBundleInterface::getAdminIframePath()` is also obsolete as there's no UI anymore in 11, so should be deprecated as well.

2022-07-18 09:11 UTC, brusch commented on bundles/CoreBundle/Command/Bundle/DisableCommand.php
> +        trigger_deprecation(
Should we maybe directly send this info to the output as well, so that you notice when manually executing it? 🤔

2022-07-18 14:14 UTC, dvesh3 commented
> I think a lot of methods in `\Pimcore\Extension\Bundle\PimcoreBundleManager` can be deprecated as well, such as `getActiveBundle()` or `enable()` and a lot more, right?
> 
> `\Pimcore\Extension\Bundle\PimcoreBundleInterface::getAdminIframePath()` is also obsolete as there's no UI anymore in 11, so should be deprecated as well.

@brusch review changes: 

- Deprecated methods related to `enable` \ `disable` states in `PimcoreBundleManager`. 
- `getActiveBundles()` & `getActiveBundle()` is not deprecated, since it also considers Kernel & manually registered bundles.
- Deprecated `PimcoreBundleInterface::getAdminIframePath()` method

2022-07-18 14:15 UTC, dvesh3 commented on bundles/CoreBundle/Command/Bundle/DisableCommand.php
> +        trigger_deprecation(
Sending deprecation info to output with verbose check.

2022-07-18 14:36 UTC, brusch commented
@dvesh3 regarding `getActiveBundles()` & `getActiveBundle()`, I'm wondering if we should rename them (incl. BC layer), because there are no "active" bundles anymore since we remove the possibility to enable/disable them? WDYT?

2022-07-18 15:07 UTC, dvesh3 commented
> @dvesh3 regarding `getActiveBundles()` & `getActiveBundle()`, I'm wondering if we should rename them (incl. BC layer), because there are no "active" bundles anymore since we remove the possibility to enable/disable them? WDYT?

@brusch As the phpdoc comment says "_List of currently active bundles from kernel_" and also there could be bundles manually registered on the kernel. The list is not based on enabled status.

2022-07-19 08:57 UTC, merged

2022-07-25 15:28 UTC, BlackbitNeueMedien commented
What is the goal of this PR? In the end it replaces `var/config/extensions.php` by `app/config/bundles.php`. 
In the past there were some changes for better cloud hosting support but here one file-based config gets exchanged for another file-based config.
Plus the addition that it is now more error-prone because you have to edit a real PHP file for installation instead of being able to execute `bin/console pimcore:bundle:enable MyBundle`.