Fix Symfony deprecations
pimcore/pimcore pull request #12635
Opened 2022-07-12 14:58 UTC by dvesh3

## Changes in this pull request  
Resolves #12551

## Additional info

2022-07-13 14:45 UTC, kingjia90 requested changes

2022-07-13 14:45 UTC, kingjia90 commented on bundles/AdminBundle/Security/User/UserProvider.php
> +        return $this->loadUserByUsername($identifier);
```suggestion
        return $this->loadUserByIdentifier($identifier);
```

2022-07-13 14:45 UTC, kingjia90 commented on bundles/AdminBundle/DependencyInjection/Compiler/LegacyAuthenticationSecurityPass.php
> +        if (!$container->getParameter('security.authenticator.manager.enabled')) {
i get an error, reads as `You have requested a non-existent parameter "security.authenticator.manager.enabled".`
it's loading `LegacyAuthenticationSecurityPass` before `AuthenticatorSecurity`, so the line `$container->setParameter('security.authenticator.manager.enabled', true);` is not set yet?

2022-07-13 14:45 UTC, kingjia90 commented on bundles/AdminBundle/DependencyInjection/Compiler/LegacyAuthenticationSecurityPass.php
> +        if (!$container->getParameter('security.authenticator.manager.enabled')) {
even after the `has` change, it doesn't work, throws an exception here 
`Invalid service "Pimcore\Bundle\AdminBundle\Security\Guard\AdminAuthenticator": the class is not set.`

2022-07-13 14:46 UTC, kingjia90 commented
These 2 are still triggered in the tests: 
- [x] `Since symfony/twig-bundle 5.2: Accessing the "twig" service directly from the container is deprecated, use dependency injection instead./home/runner/work/pimcore/pimcore/vendor/symfony/contracts/Deprecation/function.php:25`
- [x] ~`Since symfony/event-dispatcher 5.1: Symfony\Component\EventDispatcher\LegacyEventDispatcherProxy is deprecated, use the event dispatcher without the proxy./home/runner/work/pimcore/pimcore/vendor/symfony/contracts/Deprecation/function.php:25`~

are these missing here or already covered in another unmerged PR?

2022-07-13 16:34 UTC, dvesh3 commented on bundles/AdminBundle/DependencyInjection/Compiler/LegacyAuthenticationSecurityPass.php
> +        if (!$container->getParameter('security.authenticator.manager.enabled')) {
Fixed it by by checking `hasParameter('security.authenticator.manager.enabled')`

2022-07-13 17:34 UTC, kingjia90 commented on bundles/AdminBundle/DependencyInjection/Compiler/LegacyAuthenticationSecurityPass.php
> +        if (!$container->getParameter('security.authenticator.manager.enabled')) {
I've also tried with hasParameter, but it throws another problem, related to the Service not set. Have you tried to log into admin interface?

2022-07-14 07:28 UTC, dvesh3 commented on bundles/AdminBundle/DependencyInjection/Compiler/LegacyAuthenticationSecurityPass.php
> +        if (!$container->getParameter('security.authenticator.manager.enabled')) {
yes, I have fixed the service not set issue too!

2022-07-14 07:29 UTC, dvesh3 commented on bundles/AdminBundle/DependencyInjection/PimcoreAdminExtension.php
> +        if(!$container->hasParameter('pimcore_admin.security.logout_success_handler')) {
```suggestion
        if(!$container->hasParameter('security.authenticator.manager.enabled')) {
```

2022-07-14 11:06 UTC, dvesh3 commented
>Since symfony/event-dispatcher 5.1: Symfony\Component\EventDispatcher\LegacyEventDispatcherProxy is deprecated, use the event dispatcher without the proxy./home/runner/work/pimcore/pimcore/vendor/symfony/contracts/Deprecation/function.php:25

@kingjia90  I'm not really sure, where this is coming from..we don't use this proxy class anywhere in the core or Pimcore bundles.

2022-07-14 13:19 UTC, kingjia90 commented
> > Since symfony/event-dispatcher 5.1: Symfony\Component\EventDispatcher\LegacyEventDispatcherProxy is deprecated, use the event dispatcher without the proxy./home/runner/work/pimcore/pimcore/vendor/symfony/contracts/Deprecation/function.php:25
> 
> @kingjia90 I'm not really sure, where this is coming from..we don't use this proxy class anywhere in the core or Pimcore bundles.

Ok, it seems that some symfony components have a bc layer that reference this 
https://github.com/symfony/mailer/blob/57384499f838a00776fb1d9e58f7e6e1a706cf71/Mailer.php#L39
and probably it triggers the notice when composer autoloads (i can find LegacyEventDispatcherProxy in `/vendor/composer/autoload_classmap.php`)
https://github.com/symfony/event-dispatcher/blob/8e6ce1cc0279e3ff3c8ff0f43813bc88d21ca1bc/LegacyEventDispatcherProxy.php#L16

2022-07-14 13:22 UTC, kingjia90 approved these changes

2022-07-14 13:50 UTC, merged