Add upgrade notes and docs for JS events
pimcore/pimcore pull request #12633
Opened 2022-07-12 14:17 UTC by robertSt7

resolves #12591

2022-07-13 13:58 UTC, mcop1 commented on bundles/AdminBundle/Resources/public/js/pimcore/plugin/broker.js
> +            const warnText = `Plugins are depreacted. Please use event listener - ${plugin.getClassName()}::${event}`;
```suggestion
            const warnText = `Plugins are deprecated. Please use event listener - ${plugin.getClassName()}::${event}`;
```

2022-07-13 13:58 UTC, mcop1 commented on doc/Development_Documentation/20_Extending_Pimcore/13_Bundle_Developers_Guide/06_Event_Listener_UI.md
> +Pimcore supports i18n for UI extensions. Fist see the [i18n section for bundles](./README.md) how to prepare the data
```suggestion
Pimcore supports i18n for UI extensions. Fist see the [i18n section for bundles](./README.md) how to prepare the data 
```
```suggestion
Pimcore supports i18n for UI extensions. First see the [i18n section for bundles](./README.md) how to prepare the data 
```

2022-07-13 13:58 UTC, mcop1 commented on doc/Development_Documentation/23_Installation_and_Upgrade/07_Updating_Pimcore/README.md
>  ## Upgrading to Version X from earlier Versions
```suggestion
## Upgrading from earlier Versions
```

2022-07-13 14:32 UTC, jdreesen commented on doc/Development_Documentation/23_Installation_and_Upgrade/07_Updating_Pimcore/README.md
> +- [Upgrade from Version 10 to Version XI](./11_V10_to_V11.md)
Why not:

```suggestion
- [Upgrade from Version X to Version XI](./11_V10_to_V11.md)
```

2022-07-14 10:11 UTC, brusch requested changes

2022-07-14 10:11 UTC, brusch commented on doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
> +- [JS Events/Disabled] The plugin broker for fire events has been disabled.
Here we should include a link to the event listener docs.

2022-07-14 10:11 UTC, brusch commented on doc/Development_Documentation/20_Extending_Pimcore/13_Bundle_Developers_Guide/06_Event_Listener_UI.md
>  | Name                                 | Description                                                                                                     | Notes    |
I think we could remove the table from here and just move the event descriptions over to the JS file. Then we have just one place to maintain the stuff and we are doing the same for the PHP events.

2022-07-14 10:11 UTC, brusch commented on doc/Development_Documentation/20_Extending_Pimcore/13_Bundle_Developers_Guide/06_Event_Listener_UI.md
> +this.navEl = Ext.get('pimcore_menu_search').insertSibling('<li id="pimcore_menu_mds" data-menu-tooltip="mds extension" class="pimcore_menu_item pimcore_menu_needs_children">mds extension</li>', 'afte
I think we should use a local variables here `var` should be sufficient here, right?

2022-07-15 08:49 UTC, merged