Added a method to return publicly available full url path of the thumbnail
pimcore/pimcore pull request #12657
Opened 2022-07-15 04:46 UTC by aashan10

## Changes in this pull request  
Resolves #11692

2022-07-15 07:53 UTC, brusch commented on models/Asset/Thumbnail/ImageThumbnailTrait.php
> +        return Tool::getHostUrl() . $this->getPath($deferred);
This is not entirely right, what about remote object storages such as S3? 
Those are handled here: https://github.com/pimcore/pimcore/blob/10.x/models/Asset/Thumbnail/ImageThumbnailTrait.php#L314

2022-07-18 09:05 UTC, jdreesen commented on models/Asset/Thumbnail/ImageThumbnailTrait.php
> +    }
Why does this, unlike [`getPath()`](https://github.com/pimcore/pimcore/blob/10.x/models/Asset/Document/ImageThumbnail.php#L64-L77) (or [this](https://github.com/pimcore/pimcore/blob/10.x/models/Asset/Video/ImageThumbnail.php#L70-L83), or [this](https://github.com/pimcore/pimcore/blob/10.x/models/Asset/Image/Thumbnail.php#L57-L91)), not dispatch an event?

2022-07-18 09:48 UTC, brusch requested changes
This is still not right, see my last comment, because the return value of `convertToWebPath()` can already include an absolute path, e.g. when using `frontend_prefixes` config.

2022-07-18 09:58 UTC, brusch requested changes

2022-07-18 09:58 UTC, brusch commented on models/Asset/Thumbnail/ImageThumbnailTrait.php
> +    }
```suggestion
    /**
     * @return string
     */
    public function getFrontendPath(): string
    {
        $path = $this->getPath();
        if(!\preg_match('@^(https?|data):@', $path)) {
            $path = \Pimcore\Tool::getHostUrl() . $path;
        }

        return $path;
    }
```

This should do the trick, imho.

2022-07-18 12:24 UTC, brusch commented on models/Asset/Thumbnail/ImageThumbnailTrait.php
> +    }
If we change to the suggested approach, an additional event shouldn't be necessary, as `getPath()` is called anyway 😊

2022-07-20 09:34 UTC, merged

2022-07-20 17:10 UTC, dasraab commented
i think that is still not correct because you are not able to get a frontend path (with frontend_prefixes) when calling getFrontendPath() in a console command.

[see ImageThumbnailTrait.php#L320](https://github.com/pimcore/pimcore/blob/b234d787fcc7908d3855c729a0f24ed2368788f2/models/Asset/Thumbnail/ImageThumbnailTrait.php#L320)

maybe you should also consider to use symfonys built in router-configuration to set the default uri for the application:
[Generating URLs in Commands](https://symfony.com/doc/5.3/routing.html#generating-urls-in-commands)

2024-06-13 05:24 UTC, cancan101 commented
How does `getFrontendPath` compare to `getFrontendFullPath`? I can't tell from the docs what the difference is.