Sort Predefined Document Types
pimcore/pimcore pull request #12708
Opened 2022-07-20 12:52 UTC by NiklasBr

## Changes in this pull request  

Sorts by priority first and name second

2022-07-20 15:48 UTC, NiklasBr commented
Reason for the JS change is this:

![image](https://user-images.githubusercontent.com/279826/180023181-7821f10f-c506-4c4d-8af2-2edf5e53dd67.png)

*1* is first priority
*10* is last priority as shown in the select options

It also makes sense, which comes first when sorting naturally. It is also [how others](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Render%21Element%21Weight.php/9.4.x) [do it](https://www.man7.org/linux/man-pages/man2/getpriority.2.html).

2023-01-10 10:14 UTC, mattamon commented
Hey @NiklasBr,

Thank you for your contribution.
It makes totally sense to sort it that way. I also checked the priority for the doc types and it appears the priority is never used anyways. 

Atm the priority is a select with 10 entries. Once you changed it, you cannot change it back to 0. 
I think it would make more sense if it was just a number input? Why would we restrict it to 10 anyways? Wdyt?
 
There is also an api involved that can read the docTypes via this route: `pimcore_admin_document_document_doctypesget`
It would make sense to change the sorting there too right?

2023-01-11 13:40 UTC, NiklasBr commented
Sounds good, will see what I can do

2023-01-11 14:56 UTC, jdreesen commented on models/Document/DocType/Listing/Dao.php
> +            usort($docTypes, [self::class, 'sortByPriority']);
PHP 8.1 :tada: 

```suggestion
            usort($docTypes, self::sortByPriority(...)]);
```

2023-01-11 15:08 UTC, NiklasBr commented on models/Document/DocType/Listing/Dao.php
> +            usort($docTypes, [self::class, 'sortByPriority']);
Nice 👍

2023-01-12 07:41 UTC, mattamon requested changes
I noticed that I cannot update Document Types either with an empty Controller or an empty template due to the param types of the setter methods not being nullable. 

```php
   public function setController(string $controller): static
    {
        $this->controller = $controller;

        return $this;
    }
```
Maybe we can change this in this PR as well so it works properly again?

2023-01-12 07:41 UTC, mattamon commented on bundles/AdminBundle/public/js/pimcore/settings/docTypes.js
> +                    allowBlank: true,
If we allow "blank" or null here we have to change setPriority method to allow null. We should then also remove the int cast. If we do not allow null values we could still remove the int cast though :D 
Currently it looks like the following:
```php
   public function setPriority(int $priority): static
    {
        $this->priority = (int) $priority;

        return $this;
    }
```

2023-01-12 09:55 UTC, mattamon requested changes
I will open a separate Issue for the Controller and the Template not being nullable. :)

2023-01-12 09:55 UTC, mattamon commented on bundles/AdminBundle/public/js/pimcore/settings/docTypes.js
> +                    minValue: 1,
Sorry about this one, but I mentioned it in the review before :) 
If the min value is 1 and the initial value is 0, you cannot change back to the initial value once you set the priority. So I would keep it at 0 tbh.
```suggestion
                    minValue: 0,
```

2023-01-12 10:26 UTC, mattamon approved these changes

2023-01-12 10:29 UTC, merged