[Bug]: Fix Video Datatype not supporting allowedTypes
pimcore/pimcore pull request #12846
Opened 2022-08-08 22:26 UTC by kingjia90

## Changes in this pull request  
Resolves #12832

## Additional info  

The problem was caused by the introduction of this feature `allowedTypes` in Video Editables introduced with
https://github.com/pimcore/pimcore/pull/12445 where `openVideoEditPanel` got changed along the editable
https://github.com/pimcore/pimcore/blob/1c3b20e530e9568f9d80bf8fa5c8b32b5400ac24/bundles/AdminBundle/Resources/public/js/pimcore/document/editables/video.js#L58 
but didn't cover the video datatype which uses the same helper https://github.com/pimcore/pimcore/blob/b675696e8c3dff29e51d97e67fc79d3003c9ca3a/bundles/AdminBundle/Resources/public/js/pimcore/object/tags/video.js#L138

even though it can look like an improvement by adding this
![image](https://user-images.githubusercontent.com/6014195/183525141-35f669f3-1923-4a80-879b-48e321fd62e2.png)
 it should be a bug fix 😄

2022-08-08 22:44 UTC, kingjia90 commented
TODO: The constants need to be refactored to avoid duplicate code

2022-08-17 07:31 UTC, aashan10 approved these changes

2022-08-17 07:58 UTC, brusch requested changes, later dismissed

2022-08-17 07:58 UTC, brusch commented on models/DataObject/ClassDefinition/Data/Video.php
> +    public const ALLOWED_TYPES = [
Don't think we need this constant, because we're not reusing this anyway.

2022-08-17 07:58 UTC, brusch commented on models/DataObject/ClassDefinition/Data/Video.php
> +    public $videoTypes = self::ALLOWED_TYPES;
This feels like a workaround, probably it's better to use `FieldDefinitionEnrichmentInterface`
See https://github.com/pimcore/pimcore/blob/6245efe3be3d64ca5f3369a8472533f98d73043e/models/DataObject/ClassDefinition/Data/Multiselect.php#L713 for an example.

2022-08-17 15:14 UTC, merged