[Bug]: Asset Folder Preview tab supporting audio files and other files formats
pimcore/pimcore pull request #12880
Opened 2022-08-11 19:23 UTC by kingjia90

## Changes in this pull request  
Resolves https://github.com/pimcore/pimcore/issues/12808

2022-08-12 07:10 UTC, brusch requested changes

2022-08-12 07:10 UTC, brusch commented on bundles/AdminBundle/Controller/Admin/Asset/AssetController.php
> +            return $asset->getFallbackThumbnailUrl();
As this is entirely admin functionality, I'd just put the whole logic here. Imho the icon image shouldn't be defined in the model.

2022-08-16 08:15 UTC, brusch submitted a review, later dismissed

2022-08-16 08:15 UTC, brusch commented on bundles/AdminBundle/Controller/Admin/Asset/AssetController.php
> +        if ($asset instanceof Asset\Folder) {
```suggestion
        if ($asset instanceof Asset\Audio) {
```

2022-08-17 07:52 UTC, aashan10 approved these changes

2022-08-17 09:45 UTC, merged