Remove deprecated \Doctrine\DBAL\Connection class
pimcore/pimcore pull request #12917
Opened 2022-08-19 09:29 UTC by blankse

Followup to https://github.com/pimcore/pimcore/issues/12363

2022-08-19 11:12 UTC, blankse commented
See also https://github.com/pimcore/pimcore/pull/12919 for 10.5 branch

2022-08-22 10:11 UTC, brusch requested changes

2022-08-22 10:11 UTC, brusch commented on doc/Development_Documentation/26_Best_Practice/55_Primary-Replica_Database_Connection.md
> -**IMPORTANT**: Please be aware that the primary/replica connection can only be used for a clustered MariaDB/MySQL environment, **NOT**
This is still relevant information. 
I'd keep that page and for configuration I'd link to the official primary/replica docs of Doctrine Bundle. WDYT?

2022-08-22 10:13 UTC, brusch commented
Related to #10613

2022-08-22 12:20 UTC, brusch commented
@blankse as https://github.com/pimcore/pimcore/pull/12919 got merged, this PR causes conflicts, can you please check & fix them - thanks a lot 😊

2022-08-22 12:29 UTC, blankse commented
@brusch I merged 10.5 branch and resolve the conflicts. I also added the replica docs again. Can you test it if it works?

2022-08-22 13:02 UTC, brusch commented
@blankse can you merge `11.x` branch again? Thanks!

2022-08-22 13:04 UTC, blankse commented
@brusch Done

2022-08-22 13:33 UTC, brusch requested changes

2022-08-22 13:33 UTC, brusch commented on doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
> +  Column identifiers for the `insert()` method data must be self quoted now. You can use the `Pimcore\Db\Helper::quoteDataIdentifiers()` method for that.
```suggestion
  Column identifiers for the `insert()` and `update()` method data must be self quoted now. You can use the `Pimcore\Db\Helper::quoteDataIdentifiers()` method for that.
```

2022-08-22 13:33 UTC, brusch commented on doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
> +  Column identifiers for the `insert()` method data must be self quoted now. You can use the `Pimcore\Db\Helper::quoteDataIdentifiers()` method for that.
@blankse I'm afraid that this change (no auto quoting anymore of column names) has some bigger impact and needs some more attention, e.g. here: 

https://github.com/pimcore/pimcore/blob/cd48e25f5c80052e73cc378d77b18effba5c111f/models/Document/Dao.php#L84

2022-08-23 06:31 UTC, blankse commented on doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
> +  Column identifiers for the `insert()` method data must be self quoted now. You can use the `Pimcore\Db\Helper::quoteDataIdentifiers()` method for that.
@brusch This insert is already customized. But I'm looking for other insert/update methods.

2022-08-23 08:58 UTC, brusch commented on doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
> +  Column identifiers for the `insert()` method data must be self quoted now. You can use the `Pimcore\Db\Helper::quoteDataIdentifiers()` method for that.
@blankse cool, thanks! 😊

2022-08-30 08:05 UTC, aashan10 approved these changes

2022-08-30 08:14 UTC, merged

2022-08-30 08:14 UTC, brusch commented
Thank you very much 👍