[Installer] Fix creating "system" user
pimcore/pimcore pull request #13001
Opened 2022-08-30 11:03 UTC by dvesh3

## Changes in this pull request  
Always create a system user with `id = 0`, irrespective of data dump provided.

## Additional info

2022-08-30 12:10 UTC, brusch requested changes

2022-08-30 12:10 UTC, brusch commented on bundles/CoreBundle/Migrations/Version20220830105212.php
> +        $this->addSql("DELETE FROM users WHERE `id` = 0");
I'm sure about this, because the entry could have been there before, so maybe we just kick that, as it doesn't hurt anyway. WDYT?

2022-08-30 12:30 UTC, dvesh3 commented on bundles/CoreBundle/Migrations/Version20220830105212.php
> +        $this->addSql("DELETE FROM users WHERE `id` = 0");
this was my first  thought too! kicked it 😉

2022-08-30 12:42 UTC, blankse commented on bundles/InstallBundle/Installer.php
> +    protected function insertSystemUser(Connection $db)
```suggestion
    protected function insertSystemUser(Connection $db): void
```

2022-08-30 14:10 UTC, aryaantony92 commented on bundles/CoreBundle/Migrations/Version20220830105212.php
> +        $this->addSql("INSERT IGNORE INTO users (`parentId`, `name`, `admin`, `active`) VALUES(0, 'system', 'admin', 'active');");
```suggestion
        $this->addSql("INSERT IGNORE INTO users (`parentId`, `name`, `admin`, `active`) VALUES(0, 'system', 1, 'active');");
```

2022-08-30 14:35 UTC, merged

2022-09-01 13:39 UTC, Fahl-Design commented
@aryaantony92 @brusch @blankse Guess what happens when updating an existing install ;)

```
[notice] Migrating up to Pimcore\Bundle\CoreBundle\Migrations\Version22020614115124
[error] Migration Pimcore\Bundle\CoreBundle\Migrations\Version20220830105212 failed during Execution. Error: "An exception occurred while executing 'UPDATE users set id = 0 where name = 'system'':

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'users.PRIMARY'"

In AbstractMySQLDriver.php line 74:
                                                                               
  An exception occurred while executing 'UPDATE users set id = 0 where name =  
   'system'':                                                                  
                                                                               
  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' f  
  or key 'users.PRIMARY'                                                       
                                                                               
```

2022-09-01 13:46 UTC, dvesh3 commented
@Fahl-Design do you have a user with `id = 0` & name is not `system` in users table? if yes, could you please share some info of this entry? thanks!

2022-09-01 13:49 UTC, Fahl-Design commented
@dvesh3 my system user already had `id = 0`

2022-09-01 13:54 UTC, dvesh3 commented
I wonder then why you are getting the duplicate entry error as we are updating the same row.

2022-09-01 14:03 UTC, Fahl-Design commented
hmmm looks like my sql server is not CaseSensetive

![image](https://user-images.githubusercontent.com/6690962/187933352-829da724-46eb-4fd4-a23b-9109489b79d8.png)

updating with `name = "system"` tries to update 2 entries and results in duplication error

2022-09-01 14:08 UTC, dvesh3 commented
Ok, this is reproducible. we need to fix the migration with type in where condition.