Add possibility to download asset in relations
pimcore/pimcore pull request #13147
Opened 2022-09-13 20:24 UTC by dpfahlbusch

## Changes in this pull request  
Resolves #7633

## Additional info

2022-09-15 09:26 UTC, brusch commented
I'm wondering if that is really a very common use case ... maybe we should keep that configurable, or just provide the functionality in the context menu? Just thinking, because we actually have already quite some buttons there 😉

2022-09-15 09:56 UTC, dpfahlbusch commented
You mean adding a new checkbox in classconfig for relations ("allow inline download" or something like that)? :)

2022-09-15 10:01 UTC, brusch commented
Yeah, something like that. Or maybe we could even think about a more generic approach where you can configure the available buttons incl. adding your own buttons (or bundles) - which is then similar to use in all data-types? 🤔

2022-09-18 18:39 UTC, dpfahlbusch commented
So I would say:
In a first step I will make the buttons configurable (all of them or only a few? 🤔 )
And then in a followup we can make it generic :)

2022-09-18 20:33 UTC, blankse requested changes

2022-09-18 20:33 UTC, blankse commented on models/DataObject/ClassDefinition/Data/ManyToManyRelation.php
> +    public bool $assetInlineDownloadAllowed;
```suggestion
    public bool $assetInlineDownloadAllowed = false;
```

2022-09-18 20:33 UTC, blankse commented on models/DataObject/ClassDefinition/Data/ManyToManyRelation.php
> +    public function setAssetInlineDownloadAllowed(bool $assetInlineDownloadAllowed): self
```suggestion
    /**
     * @return $this
     */
    public function setAssetInlineDownloadAllowed(bool $assetInlineDownloadAllowed): static
```

2022-09-18 20:48 UTC, dpfahlbusch commented on models/DataObject/ClassDefinition/Data/ManyToManyRelation.php
> +    public bool $assetInlineDownloadAllowed;
Done with last commit :)

2022-09-18 20:48 UTC, dpfahlbusch commented on models/DataObject/ClassDefinition/Data/ManyToManyRelation.php
> +    public function setAssetInlineDownloadAllowed(bool $assetInlineDownloadAllowed): self
Done with last commit :)

2022-10-05 12:08 UTC, robertSt7 approved these changes
@dpfahlbusch When I try to download a folder I got an error. Could you please check that?
Could you also please add some docs. Thank you

2022-10-05 12:08 UTC, robertSt7 commented on bundles/AdminBundle/public/js/pimcore/object/tags/advancedManyToManyRelation.js
> +                            var data = grid.getStore().getAt(rowIndex);
```suggestion
                            const data = grid.getStore().getAt(rowIndex);
```

2022-10-05 12:08 UTC, robertSt7 commented on bundles/AdminBundle/public/js/pimcore/object/tags/manyToManyRelation.js
> +                            var data = grid.getStore().getAt(rowIndex);
```suggestion
                            const data = grid.getStore().getAt(rowIndex);
```

2022-10-07 10:11 UTC, robertSt7 commented
@dpfahlbusch Could you please fix the conflicts. Thanks

2022-10-07 10:17 UTC, dpfahlbusch commented
@robertSt7 done :)

2022-10-10 08:00 UTC, robertSt7 commented
@dpfahlbusch Could you please merge 11.x again in your branch? Thanks :)

2022-10-10 10:19 UTC, merged

2022-10-10 10:19 UTC, robertSt7 commented
@dpfahlbusch Thanks a lot :)