Make editmodeImagePreview available for YouTube videos
pimcore/pimcore pull request #13151
Opened 2022-09-14 13:01 UTC by bitfactory-jurgen-jansma

## Changes in this pull request  
The config `editmodeImagePreview` for the video editable was not working for YouTube videos. I made it working in this pull request. 

## Additional info  
I'm not sure if you see this as a bug fix or as a feature/improvement. But, in our case, this solves a bug in loading the editor in the admin panel, so that's why I submitted this pull request in 10.5.

2022-09-15 09:48 UTC, brusch commented
@bitfactory-jurgen-jansma thanks a lot for your PR! 
2 thinks we should consider as well: 
1. We should also use `$inAdmin` argument for `getYoutubeCode()` same as for `getAssetCode()`, see: https://github.com/pimcore/pimcore/blob/b447bc02341a2eb097bc48c2f6e9f3f84d708829/models/Document/Editable/Video.php#L457
2. to be consisten we should try to fix that for Vimeo and Dailymotion as well

Thanks a lot!

2022-09-15 10:29 UTC, bitfactory-jurgen-jansma commented
@brusch thank you for your review. I have used the `$inAdmin` argument instead of `$this->editmode` now. I have also added a thumbnail for Vimeo and Dailymotion as well.

2022-09-15 10:56 UTC, blankse requested changes
Please use type hints for new params

2022-09-15 10:56 UTC, blankse commented on models/Document/Editable/Video.php
> +    private function getYoutubeCode($inAdmin = false)
```suggestion
    private function getYoutubeCode(bool $inAdmin = false): string
```

2022-09-15 10:56 UTC, blankse commented on models/Document/Editable/Video.php
> +    private function getVimeoCode($inAdmin = false)
```suggestion
    private function getVimeoCode(bool $inAdmin = false): string
```

2022-09-15 10:56 UTC, blankse commented on models/Document/Editable/Video.php
> +    private function getDailymotionCode($inAdmin = false)
```suggestion
    private function getDailymotionCode(bool $inAdmin = false): string
```

2022-09-15 10:56 UTC, blankse commented on models/Document/Editable/Video.php
>       */
```suggestion
```

2022-09-15 10:56 UTC, blankse commented on models/Document/Editable/Video.php
>       */
```suggestion
```

2022-09-15 10:56 UTC, blankse commented on models/Document/Editable/Video.php
>       */
```suggestion
```

2022-09-15 11:05 UTC, bitfactory-jurgen-jansma commented
@blankse I didn't add the type hinting because it wasn't use yet, and I expected that it wasn't there for a reason. However, I have added the type hinting to all edited methods.

2022-09-28 12:25 UTC, brusch commented
Failing Codeception tests are not related to this PR ... caused by #13171 (fix)

2022-09-28 12:25 UTC, merged