Add type hints to private methods
pimcore/pimcore pull request #13194
Opened 2022-09-19 12:35 UTC by blankse

Add type hints to all private methods and removes redundant php docs.

2022-10-06 09:36 UTC, aashan10 requested changes

2022-10-06 09:36 UTC, aashan10 commented on bundles/AdminBundle/src/Controller/Admin/Document/PrintpageControllerBase.php
> +    private function getStoredProcessingOptions(int $documentId): mixed
Since we are already using php 8.0 wouldn't it be good if we used union type here instead of eliminating the array return type?

2022-10-06 09:36 UTC, aashan10 commented on bundles/EcommerceFrameworkBundle/Type/Decimal.php
> +    private function getScalarOperand(mixed $operand): float|int|string
Can we make this consistent with previous docblock return type somehow? Maybe cast the value to float before returning?

2022-10-06 09:36 UTC, aashan10 commented on lib/Workflow/MarkingStore/DataObjectSplittedStateMarkingStore.php
> +    private function setProperty(Concrete $subject, string $property, mixed $places): void
```suggestion
    private function setProperty(Concrete $subject, string | PropertyPathInterface $property, mixed $places): void
```

2022-10-06 09:36 UTC, aashan10 commented on models/DataObject/ClassDefinition/Data/EncryptedField.php
> +    private function decrypt(?string $data, Model\DataObject\Concrete $object, array $params)
```suggestion
    private function decrypt(?string $data, Model\DataObject\Concrete $object, array $params): ?string
```

2022-10-06 09:36 UTC, aashan10 commented on models/DataObject/ClassDefinition/Data/Select.php
> +    private function correctColumnDefinition(string $type)
```suggestion
    private function correctColumnDefinition(string $type): void
```

2022-10-06 09:36 UTC, aashan10 commented on models/DataObject/Localizedfield.php
> -     * @internal
I'm not sure if removing `@internal` is a good idea here!

2022-10-06 09:45 UTC, blankse commented on bundles/AdminBundle/src/Controller/Admin/Document/PrintpageControllerBase.php
> +    private function getStoredProcessingOptions(int $documentId): mixed
@aashan10 array is also included in mixed. See https://www.php.net/manual/en/language.types.declarations.php#language.types.declarations.mixed

2022-10-06 09:50 UTC, blankse commented on bundles/EcommerceFrameworkBundle/Type/Decimal.php
> +    private function getScalarOperand(mixed $operand): float|int|string
Done: https://github.com/pimcore/pimcore/pull/13194/commits/c0f52cc66e4340bc01d764c42c29536d5840daea

2022-10-06 09:54 UTC, blankse commented on lib/Workflow/MarkingStore/DataObjectSplittedStateMarkingStore.php
> +    private function setProperty(Concrete $subject, string $property, mixed $places): void
@aashan10 Why? Is only called in line 118 there it should be a string. Also it is in the method use for getFieldDefinition() which only allowed string.

2022-10-06 09:57 UTC, blankse commented on models/DataObject/Localizedfield.php
> -     * @internal
@aashan10 Private methods are always internal, right?

2022-10-10 08:00 UTC, aashan10 commented on lib/Workflow/MarkingStore/DataObjectSplittedStateMarkingStore.php
> +    private function setProperty(Concrete $subject, string $property, mixed $places): void
Oh I see! Thanks.

2022-10-10 08:01 UTC, aashan10 commented on models/DataObject/Localizedfield.php
> -     * @internal
Yeah.. you're right! Thanks

2022-10-10 08:02 UTC, aashan10 approved these changes

2022-10-13 11:23 UTC, dvesh3 commented on doc/Development_Documentation/26_Best_Practice/83_Showing_Custom_Layouts_based_on_Object_Data.md
> +    private function doModifyCustomLayouts(array $data, Product $object, int $customLayoutToSelect, array $layoutsToRemove): void
```suggestion
    private function doModifyCustomLayouts(array $data, Product $object, int $customLayoutToSelect, array $layoutsToRemove): array
```

2022-10-13 11:27 UTC, dvesh3 approved these changes

2022-10-14 14:15 UTC, merged

2022-10-14 14:15 UTC, dvesh3 commented
@blankse thank you very much 💜