Feature/relational fields display mode
pimcore/pimcore pull request #13227
Opened 2022-09-22 12:44 UTC by BlackbitNeueMedien

## Changes in this pull request  
Resolves #

## Additional info

2022-09-22 12:53 UTC, blankse requested changes
Set type hints and no redundant php docs

2022-09-22 12:53 UTC, blankse commented on models/DataObject/ClassDefinition/Data/Relations/AbstractRelations.php
> +    public $displayMode;
```suggestion
    /**
     * Optional display mode
     *
     * @internal
     */
    public ?string $displayMode = null;
```

2022-09-22 12:53 UTC, blankse commented on models/DataObject/ClassDefinition/Data/Relations/AbstractRelations.php
> +    }
```suggestion
    public function getDisplayMode(): ?string
    {
        return $this->displayMode;
    }

    /**
     * @return $this
     */
    public function setDisplayMode(?string $displayMode): static
    {
        $this->displayMode = $displayMode;

        return $this;
    }
```

2022-09-22 12:53 UTC, blankse commented on bundles/AdminBundle/src/Controller/Admin/DataObject/DataObjectController.php
> +    public function optionsAction(Request $request) {
```suggestion
     */
    public function optionsAction(Request $request): JsonResponse
    {
```

2022-09-22 12:55 UTC, BlackbitNeueMedien commented
Thx @blankse, have applied the changes.

2022-10-04 12:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/pimcore/pimcore?pullRequest=13227) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/pimcore/pimcore?pullRequest=13227) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/pimcore/pimcore?pullRequest=13227) it.</sub>

2022-10-20 10:54 UTC, robertSt7 approved these changes
@BlackbitDevs  I think we should also display the default value in the ui. WDYT?

2022-10-20 10:54 UTC, robertSt7 commented on bundles/AdminBundle/public/js/pimcore/object/classes/data/advancedManyToManyObjectRelation.js
> +                value: this.datax.displayMode,
```suggestion
                value: this.datax.displayMode ?? 'grid',
```

2022-10-20 10:54 UTC, robertSt7 commented on bundles/AdminBundle/public/js/pimcore/object/classes/data/manyToManyObjectRelation.js
> +                value: this.datax.displayMode,
```suggestion
                value: this.datax.displayMode ?? 'grid',
```

2022-10-20 10:56 UTC, robertSt7 commented
When I open an object with a relation data component, I get the following error:

```
URL: /admin/object/relation-objects-list?_dc=1666262555655
Method: GET
Message: explode(): Argument #2 ($string) must be of type string, array given
Trace: 
in /var/www/html/dev/pimcore/pimcore/bundles/AdminBundle/src/Controller/Admin/DataObject/DataObjectController.php:566
#0 /var/www/html/dev/pimcore/pimcore/bundles/AdminBundle/src/Controller/Admin/DataObject/DataObjectController.php(566): explode(',', Array)
#1 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(153): Pimcore\Bundle\AdminBundle\Controller\Admin\DataObject\DataObjectController->optionsAction(Object(Symfony\Component\HttpFoundation\Request))
#2 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(75): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#3 /var/www/html/vendor/symfony/http-kernel/Kernel.php(202): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#4 /var/www/html/public/index.php(36): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#5 {main}
```

Could you please take a look at this?

And could you please also avoid using var and use let and const instead? Thank you

2022-11-03 12:34 UTC, robertSt7 commented
@BlackbitDevs Have you had time to look at my feedback?

2022-11-08 14:01 UTC, BlackbitDevs commented
@robertSt7 Have fixed it. This problem was caused when no visible fields have been selected. In this case in https://github.com/pimcore/pimcore/blob/2f46cce6e9f048ac6f68bcf7ca72f8d2829879e3/models/DataObject/ClassDefinition/Data/ManyToManyObjectRelation.php#L815-L823 do not get converted to a string.

2022-11-09 08:47 UTC, robertSt7 commented
> @robertSt7 Have fixed it. This problem was caused when no visible fields have been selected. In this case in
> 
> https://github.com/pimcore/pimcore/blob/2f46cce6e9f048ac6f68bcf7ca72f8d2829879e3/models/DataObject/ClassDefinition/Data/ManyToManyObjectRelation.php#L815-L823
> 
> do not get converted to a string.

@BlackbitDevs Thanks for that. I get the following error when I select the display mode "Tag field"

```
Status: 500 | Internal Server Error
URL: /admin/object/relation-objects-list?_dc=1667983544404
Method: GET
Message: Warning: Undefined array key "sqlCondition"
Trace: 
in /var/www/html/dev/pimcore/pimcore/bundles/AdminBundle/src/Controller/Admin/DataObject/DataObjectController.php:574
#0 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(163): Pimcore\Bundle\AdminBundle\Controller\Admin\DataObject\DataObjectController->optionsAction(Object(Symfony\Component\HttpFoundation\Request))
#1 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(75): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#2 /var/www/html/vendor/symfony/http-kernel/Kernel.php(202): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#3 /var/www/html/public/index.php(36): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#4 {main}
```

Could you please also take a look at this? Thanks

2022-11-09 10:25 UTC, BlackbitDevs commented
@robertSt7 Fixed. This was because at this time we developed this PR and #13131 in parallel but as #13131 was declined, we do not have the `sqlCondition`.

2022-11-09 13:22 UTC, robertSt7 commented
@BlackbitDevs Thank you. If I select no visible fields, then I see blank rows and empty elements in the multi-select. I think we should use the default fields id, fullpath and classname like in the grid view for this case. What do you think?

2022-11-09 13:36 UTC, robertSt7 commented
@BlackbitDevs I am also just thinking about a clear-relation-button in the "Tag field" view like in the grid view. What's your opinion about that?

2022-11-10 15:46 UTC, BlackbitDevs commented
@robertSt7 I have added the fallback when no visible fields have been set - as suggested id, fullpath and classname get displayed in this case.

The clear button imho is not necessary because clearing is very simple by just using backspace key. But if you think this is necessary, I can add it.
But for example tag mode for multiselect fields also does not have a clear button.

2022-11-14 15:11 UTC, robertSt7 commented
@BlackbitDevs You are right. We don't need a clear button. Everthing looks good now, except one thing. Could you please use 'let' and 'const' in the js files instead of 'var'? Thanks

2022-11-15 15:32 UTC, BlackbitDevs commented
@robertSt7 Now `let` gets used in the JS files.

I saw that most of the changed lines here at Github came from formatting - in PhpStorm you can ignore formatting changes, there it looks much cleaner. Of course the Github comparison distracts from the real changes. Is there any chance that you provide PhpStorm formatting rules or a bot which automatically formats the code?

2022-11-17 10:14 UTC, robertSt7 commented
@BlackbitDevs Not at the moment, but we don't want to use PhPStorm formatting rules because some developers might use other IDEs. However we would like to format our JS code like for PhP with a PHP-CS-Fixer. Suggestions are very much appreciated :)

2022-11-17 10:23 UTC, jdreesen commented
For JavaScript, that would be https://prettier.io/

2022-11-17 10:25 UTC, brusch commented
Would be time then for https://github.com/marketplace/actions/prettier-action 😊

2022-11-17 10:28 UTC, jdreesen commented
It can format your Markdown docs, too ;)

2022-11-17 12:06 UTC, merged

2022-11-17 12:06 UTC, robertSt7 commented
@BlackbitDevs Thanks for the PR