Added more methods to `Pimcore/Model/Element/ElementInterface`
pimcore/pimcore pull request #13290
Opened 2022-09-30 17:40 UTC by aashan10

## Changes in this pull request  
Resolves #12112

2022-10-04 12:46 UTC, dvesh3 reviewed
can also add `setType($type)`..right?

2022-10-04 12:58 UTC, blankse requested changes
The setters should return `$this`

2022-10-04 12:58 UTC, blankse commented on models/Element/ElementInterface.php
> +     * @return static
```suggestion
     *
     * @return $this
```

2022-10-04 12:58 UTC, blankse commented on models/Element/ElementInterface.php
> +     * @return static
```suggestion
     *
     * @return $this
```

2022-10-05 11:20 UTC, dvesh3 commented
@aashan10 please see https://github.com/pimcore/pimcore/pull/13290#pullrequestreview-1129863089

2022-10-05 11:22 UTC, aashan10 commented
Sure, I'll add the method.

2022-10-05 11:32 UTC, dvesh3 commented
@aashan10 please also add upgrade notes. thanks!

2022-10-06 10:00 UTC, jdreesen commented on models/Element/ElementInterface.php
> +     * @return static
Shouldn't this method return `$this`, too?

```suggestion
     *
     * @return $this
```

2022-10-06 10:01 UTC, blankse commented on models/Element/ElementInterface.php
> +     * @return static
```suggestion
     *
     * @return $this
```

2022-10-06 10:02 UTC, blankse commented on models/Element/ElementInterface.php
> +     * @return static
You were a few seconds faster :)

2022-10-10 11:01 UTC, merged