[Ecommerce] Token Manager: do no silently ignore errors on generation
pimcore/pimcore pull request #13314
Opened 2022-10-05 10:30 UTC by brusch

2022-10-05 11:44 UTC, blankse requested changes
Exceptions should be cast to string

2022-10-05 11:44 UTC, blankse commented on bundles/EcommerceFrameworkBundle/VoucherService/TokenManager/Pattern.php
> +            Logger::error($e);
```suggestion
            Logger::error((string) $e);
```

2022-10-05 11:44 UTC, blankse commented on bundles/EcommerceFrameworkBundle/VoucherService/TokenManager/Single.php
> +            Logger::error($e);
```suggestion
            Logger::error((string) $e);
```

2022-10-11 07:22 UTC, aashan10 approved these changes

2022-10-11 07:23 UTC, merged