fix: allow textareas to be nullable from admin
pimcore/pimcore pull request #13760
Opened 2022-12-07 10:58 UTC by dkarlovi

## Changes in this pull request  

Makes textareas nullable. Currently, once you edit it, it can never go back to `null`.

2022-12-07 11:05 UTC, dkarlovi commented
The expectation this always returns a string is weird since the parent is nullable. Is there a reason for this or is it a type error?

2022-12-14 15:13 UTC, Corepex requested changes
@dkarlovi could you please change the doctype from `string` to `string|null` - this should fix the phpstan issues

2022-12-15 13:07 UTC, dkarlovi commented
@Corepex 

> @dkarlovi could you please change the doctype from `string` to `string|null` - this should fix the phpstan issues +1

Yes, it's very clear how we can fix PHPStan complaining. the question was more why the type was as narrow as it was? If it's expected to be this narrow, we cannot just widen it since it's not invariant.

2022-12-19 09:20 UTC, mcop1 commented
Related to https://github.com/pimcore/pimcore/issues/13089

2022-12-23 09:57 UTC, Corepex commented
> @Corepex
> 
> > @dkarlovi could you please change the doctype from `string` to `string|null` - this should fix the phpstan issues +1
> 
> Yes, it's very clear how we can fix PHPStan complaining. the question was more why the type was as narrow as it was? If it's expected to be this narrow, we cannot just widen it since it's not invariant.

I think adding `null` shouldn't be a problem since the base class (`Data`) returns `mixed` ...

2022-12-27 12:22 UTC, Corepex commented
@dkarlovi friendly reminder ⏰

2023-01-02 10:28 UTC, brusch commented
@dkarlovi 🏓😊 Thanks!

2023-01-02 10:31 UTC, brusch commented
@dkarlovi nevermind, just pushed the fix directly to your PR 😉

2023-01-02 12:24 UTC, dkarlovi commented
thank you @brusch! \o/

2023-01-05 08:24 UTC, mcop1 commented
@dkarlovi Thank you for contributing. We discussed about this pr internally and we see it as kind of a change in behavior. That´s why we would like to do it in 11.x with this pr #13963.

2023-01-05 08:24 UTC, closed without merging