[Actions] PHP 8.2 Tests & Checks
pimcore/pimcore pull request #13861
Opened 2022-12-21 08:49 UTC by brusch

2022-12-21 12:43 UTC, jdreesen commented
Will Pimcore 10 also be compatible to PHP 8.2?

2022-12-21 13:22 UTC, brusch commented
@jdreesen currently we don't have this on our list, no 😬

2022-12-21 13:27 UTC, jdreesen commented
I'm just asking because [the `composer.json` suggests it is compatible](https://github.com/pimcore/pimcore/blob/10.5/composer.json#L31) (I haven't tried it, though).

2022-12-21 13:30 UTC, brusch commented
@jdreesen yep, noticed that as well 👍😉  We need to check and see, if it's easily possible I'd say it would be ok for 10.6.

2022-12-21 14:25 UTC, blankse requested changes
Add type hints

2022-12-21 14:25 UTC, blankse commented on models/DataObject/ClassDefinition/Data/Extension/ColumnType.php
> +    public $columnType = null;
```suggestion
    public array|string|null $columnType = null;
```

2022-12-21 14:25 UTC, blankse commented on models/DataObject/ClassDefinition/Data/Extension/ColumnType.php
>      public function setColumnType($columnType): static
```suggestion
    public function setColumnType(array|string $columnType): static
```

2022-12-21 14:25 UTC, blankse commented on models/DataObject/ClassDefinition/Data/Extension/QueryColumnType.php
> +    public $queryColumnType = null;
```suggestion
    public array|string|null $queryColumnType = null;
```

2022-12-21 14:25 UTC, blankse commented on models/DataObject/ClassDefinition/Data/Extension/QueryColumnType.php
>      public function setQueryColumnType($queryColumnType): static
```suggestion
    public function setQueryColumnType(array|string $queryColumnType): static
```

2022-12-22 19:04 UTC, brusch commented
Depends on #13888

2023-01-26 11:22 UTC, kingjia90 commented
Closing this PR in favor of https://github.com/pimcore/pimcore/pull/14080
As requested here https://github.com/pimcore/pimcore/pull/14080#issuecomment-1398099768

2023-01-26 11:22 UTC, closed without merging