Made method results consistent between CartItemInterface and CheckoutableInterface
pimcore/pimcore pull request #13946
Opened 2023-01-01 19:29 UTC by aashan10

…ableInterface

  
  

## Changes in this pull request  
Resolves #9405 

## Additional info

2023-01-02 13:45 UTC, dvesh3 requested changes
Also add upgrade notes for breaking changes.

2023-01-02 13:45 UTC, dvesh3 commented on bundles/EcommerceFrameworkBundle/src/Model/MockProduct.php
> +        return new Price(Decimal::create(0), new Currency('USD'));
Use `EnvironmentInterface::getDefaultCurrency` instead.

2023-01-02 13:45 UTC, dvesh3 commented on bundles/EcommerceFrameworkBundle/src/Model/AbstractProduct.php
> +        return $this->isActive();
we should still check for price with `$price->getAmount()`

2023-01-05 12:04 UTC, dvesh3 approved these changes

2023-01-11 08:06 UTC, fashxp approved these changes

2023-01-11 08:11 UTC, merged