Extracted out Google Marketing Bundle
pimcore/pimcore pull request #13943
Opened 2022-12-30 16:57 UTC by aashan10

## Changes in this pull request  
Resolves #

## Additional info

2022-12-30 22:45 UTC, jdreesen commented on bundles/GoogleMarketingBundle/public/js/startup.js
> +        let menu = event.detail.menu;
```suggestion
        const menu = event.detail.menu;
```

2023-01-02 09:27 UTC, brusch commented
@aashan10 what about the admin UI functionalities, such as: 
https://github.com/pimcore/pimcore/blob/38419b06c61565e62122e32684e37c102cbe25d2/bundles/AdminBundle/public/js/pimcore/report/analytics/settings.js#L15
https://github.com/pimcore/pimcore/blob/38419b06c61565e62122e32684e37c102cbe25d2/bundles/AdminBundle/public/js/pimcore/report/tagmanager/settings.js#L15
https://github.com/pimcore/pimcore/blob/38419b06c61565e62122e32684e37c102cbe25d2/bundles/AdminBundle/public/js/pimcore/report/webmastertools/settings.js#L15

and the connected actions and configs? 
Also I think the broken concept for the report settings is not needed anymore (see https://github.com/pimcore/pimcore/blob/38419b06c61565e62122e32684e37c102cbe25d2/bundles/AdminBundle/public/js/pimcore/report/settings.js#L15). I guess we can just put all the settings together in one file. 

Additionally I'd move the Symfony config to it's own root node, e.g. `pimcore_google_marketing`.

2023-01-02 09:29 UTC, brusch requested changes

2023-01-02 09:29 UTC, brusch commented on lib/Analytics/Google/Tracker.php
>          if ($siteConfig['gtagcode']) {
This should be moved into the bundles `src` folder.

2023-01-02 09:29 UTC, brusch commented on lib/Analytics/GoogleTagManager/EventSubscriber/TrackingCodeSubscriber.php
> +                    '@PimcoreGoogleMarketingBundle/Analytics/Tracking/GoogleTagManager/dataLayer.html.twig',
This file should be moved into the bundles `src` folder.

2023-01-18 17:16 UTC, dvesh3 commented on lib/Analytics/Config/SiteConfigProvider.php
> +namespace Pimcore\Analytics\Config;
Why moved out of Google namespace?

2023-01-18 17:16 UTC, dvesh3 commented on lib/Analytics/Config/SiteConfigProvider.php
> +namespace Pimcore\Analytics\Config;
and why this is still in the core?

2023-01-18 17:16 UTC, dvesh3 commented on lib/Analytics/Config/ConfigProvider.php
> +namespace Pimcore\Analytics\Config;
same question as SiteConfigProvider..

2023-01-18 17:16 UTC, dvesh3 commented on bundles/EcommerceFrameworkBundle/src/Tracking/Tracker/Analytics/Ecommerce.php
> +use Pimcore\Bundle\GoogleMarketingBundle\Analytics\Google\Tracker as GoogleTracker;
`EcommerceBundle` depends on `GoogleMarketingBundle` so it should require it.

2023-01-18 17:16 UTC, dvesh3 commented on bundles/EcommerceFrameworkBundle/src/Tracking/Tracker/Analytics/Ecommerce.php
> +use Pimcore\Bundle\GoogleMarketingBundle\Analytics\Google\Tracker as GoogleTracker;
wait for merge of https://github.com/pimcore/pimcore/pull/14042 and then we can add it to the `composer.json`

2023-01-18 17:16 UTC, dvesh3 commented on bundles/GoogleMarketingBundle/public/js/reports/analytics/elementexplorer.js
> +pimcore.registerNS("pimcore.google_marketing.report.analytics.element_explorer");
fix folder name from `reports` to `report`

2023-01-18 18:11 UTC, aashan10 commented on lib/Analytics/Config/SiteConfigProvider.php
> +namespace Pimcore\Analytics\Config;
Moved it to google marketing bundle

2023-01-30 13:13 UTC, mattamon commented
Can you please resolve the conflicts? :)

2023-01-31 07:40 UTC, mattamon commented
Please check the tests. Those are all failing atm :)

2023-02-02 15:10 UTC, dvesh3 commented on bundles/EcommerceFrameworkBundle/src/Tracking/Tracker/Analytics/Ecommerce.php
> +use Pimcore\Bundle\GoogleMarketingBundle\Analytics\Google\Tracker as GoogleTracker;
we should add this bundle requirement in ecommerce composer.json

2023-02-03 10:40 UTC, mattamon requested changes
I found the a reference of the report.custom in the cmf.
https://github.com/pimcore/customer-data-framework/blob/4.x/src/Resources/public/js/pimcore/report/custom/definitions/termSegmentBuilder.js#L14

Should there be a follow up since it has a dependency?

Overall the bundle is not really usable or testable at the moment. 
Please adapt all the requested changes.

2023-02-03 10:40 UTC, mattamon commented on bundles/GoogleMarketingBundle/src/Installer.php
> +        foreach (self::USER_PERMISSIONS as $permission) {
Since the permissions are shared and not only for the MarketingBundle, we cannot simply remove them, when you uninstall the bundle. E.g. what would happen if the custom reports bundle is installed and you uninstall the MarketingBundle? Then you would lose those permissions and you could not access the custom reports anymore.
Same goes for the system_settings. These settings are installed by default. We cannot simply remove them.

2023-02-03 10:40 UTC, mattamon commented on bundles/GoogleMarketingBundle/src/PimcoreGoogleMarketingBundle.php
> +use Pimcore\Bundle\GoogleMarketingBundle\DependencyInjection\PimcoreGoogleMarketingExtension;
We can remove this line right?

2023-02-03 10:40 UTC, mattamon commented on bundles/GoogleMarketingBundle/src/PimcoreGoogleMarketingBundle.php
> +use Symfony\Component\DependencyInjection\Extension\ExtensionInterface;
Also this line can be removed?

2023-02-03 10:40 UTC, mattamon commented on bundles/GoogleMarketingBundle/config/pimcore/config.yaml
> +    - { resource: ../event_listeners.yaml }
do we really have to load the event listeners in the config here? 
Normally they should then be in the pimcore folder right? You can also load the event listeners in the PimcoreGoogleMarketingExtension then and I am not sure if we should have a dedicated yaml for three listeners

2023-02-03 10:40 UTC, mattamon commented on bundles/GoogleMarketingBundle/public/js/startup.js
> +var google_marketing_bundle = new pimcore.bundle.google_marketing.startup();
Please change this so it matches with e.g. the GlossaryBundle -> pimcoreBundleGlossary

2023-02-03 10:40 UTC, mattamon commented on bundles/GoogleMarketingBundle/public/js/startup.js
> +pimcore.registerNS('pimcore.bundle.google_marketing.startup');
We can remove the _ -> googlemarketing is fine, see fileexplorer bunlde

2023-02-03 10:40 UTC, mattamon commented on bundles/GoogleMarketingBundle/public/js/report/tagmanager/settings.js
> +pimcore.report.settings.broker.push("pimcore.google_marketing.report.tag_manager.settings");
we should keep the tagmanager instead of tag_manager please

2023-02-03 10:40 UTC, mattamon commented on bundles/GoogleMarketingBundle/public/js/report/webmastertools/settings.js
> +pimcore.report.settings.broker.push("pimcore.google_marketing.report.webmaster_tools.settings");
same for here. please use webmastertools instead of webmaster_tools

2023-02-03 10:40 UTC, mattamon commented on bundles/GoogleMarketingBundle/public/js/report/analytics/elementexplorer.js
> +pimcore.registerNS("pimcore.google_marketing.report.analytics.element_explorer");
Please keep it as elementexplorer not element_explorer

2023-02-03 10:40 UTC, mattamon commented on bundles/GoogleMarketingBundle/public/js/report/analytics/elementexplorer.js
>  if(pimcore.bundle && pimcore.bundle.customreports) {
This check does not seem to work. I do not have the custom reports bundle installed and get the following error in the console `Uncaught TypeError: Cannot read properties of undefined (reading 'addGroup')`

2023-02-03 10:40 UTC, mattamon commented on bundles/GoogleMarketingBundle/public/js/startup.js
> +            pimcore.globalmanager.add("reports_settings", new pimcore.report.settings());
what happens when the custom reports bundle is not installed nor enabled? this won't work right?
It should still show all the other settings that are available.

the class pimcore.report.settings() also does not exist anymore with the bundle refacotoring of the custom reports

2023-02-03 10:40 UTC, mattamon commented on bundles/AdminBundle/templates/admin/index/index.html.twig
> +    "pimcore/report/custom/item.js",
These files resulting in a 404 error. 
These files do not exist anymore right and should either be loaded by the CustomReportsBundle or the GoogleMarketingBundle itself?

2023-02-09 11:18 UTC, mattamon commented
Closing in favor of #14276

2023-02-09 11:18 UTC, closed without merging