Extracted uuid to bundle
pimcore/pimcore pull request #13945
Opened 2023-01-01 17:23 UTC by aashan10

## Changes in this pull request  
Resolves #12532 

## Additional info

2023-01-10 10:17 UTC, mattamon requested changes
Can you please check this changes according to the refactoring tips too?

2023-01-11 14:02 UTC, mattamon commented
@aashan10 can you please merge in the latest 11.x updates, so the tests run trough again?

2023-01-12 15:40 UTC, mattamon approved these changes

2023-01-13 08:49 UTC, dvesh3 commented on bundles/UuidBundle/config/pimcore/default.yaml
> +    instance_identifier:  abcde
Is it needed?

2023-01-13 09:01 UTC, dvesh3 commented on bundles/UuidBundle/src/PimcoreUuidBundle.php
> +    }
```suggestion

```

2023-01-13 09:42 UTC, dvesh3 requested changes
- [ ]  Add core migration to mark the bundle installed.
- [ ]  Dao class mapping should be moved too https://github.com/pimcore/pimcore/blob/83142b53cfd5a791e3c6167470a66336fd03da22/config/dao-classmap.php#L157-L158

- [ ] Update docs that feature requires bundle to be installed https://github.com/pimcore/pimcore/blob/6c986c25fd2dc2c969840f2f0f05fd00afae31e2/doc/Development_Documentation/19_Development_Tools_and_Details/19_UUID_Support.md#L1

2023-01-16 08:17 UTC, dvesh3 approved these changes

2023-01-16 08:17 UTC, merged