[Data objects] Relations get truncated when using multiple object bricks
pimcore/pimcore pull request #13974
Opened 2023-01-04 12:53 UTC by BlackbitDevs

Steps to reproduce bug:
1. Disabling autosave makes it easier to find the cause of the problem (but the effect is also visible with autosave)
1. Create data object class with an object brick container field `aaaaaa` (sorry for bad naming but I did want to change it here to keep the logs correct)
2. Create object brick `A`, allow it for above object brick container field, add a localized many-to-many object relation field named `relationA` which allows above data object to be assigned (either all classes or only above class)
3. Create object brick `B`, allow it for above object brick container field, add a localized many-to-many object relation field named `relationB` (either all classes or only above class)
4. Create object of above class, add brick `A`, assign the object itself to `relationA`, save & publish
5. Add brick `B` , assign the object itself to `relationB`, save & publish
6. Reload object

Result: `relationA` is empty afterwards

__Cause__

When saving the localized field data we get to
https://github.com/pimcore/pimcore/blob/c53c3312701bfa0e6464d49940dbd2f718f9c854/models/DataObject/Localizedfield/Dao.php#L91-L94
(because `$this->model->hasDirtyLanguages()` is `true`)

There the relation data gets removed for localized relation fields in https://github.com/pimcore/pimcore/blob/c53c3312701bfa0e6464d49940dbd2f718f9c854/models/DataObject/Localizedfield/Dao.php#L550-L564
(Because `$container instanceof DataObject\Fieldcollection\Definition` is `true` because `Pimcore\Model\DataObject\Objectbrick\Definition` extends `DataObject\Fieldcollection\Definition`)

Here the column `ownername` gets used to find the relation fields for the object brick.

The SQL query being executed is `DELETE FROM object_relations_6 WHERE src_id = '1189' AND ownertype = 'localizedfield' AND ownername LIKE '/objectbrick~aaaaaa//%'"`

When I looked at the data in the `object_relations_<class id>` table, I wondered that the brick name is nowhere. 
<img width="997" alt="Bildschirmfoto 2023-01-05 um 12 37 26" src="https://user-images.githubusercontent.com/8749138/210771824-11d063d8-389a-41a5-ae70-584d49e85b46.png">

But this gets done for both bricks in the same way. This means that when the first brick gets saved, everything works but then the second brick gets saved and removes the relation data from the first brick because there is no filtering done for the brick name.

When the data gets saved, the `ownername` gets defined in
https://github.com/pimcore/pimcore/blob/c53c3312701bfa0e6464d49940dbd2f718f9c854/models/DataObject/Traits/ContextPersistenceTrait.php#L60-L64

I saw that `$index` is empty for object bricks which leads to `ownername` like above `/objectbrick~aaaaaa//localizedfield~localizedfield`
With this PR the brick name gets added to `ownername` so that it ends up like `/objectbrick~aaaaaa/A/localizedfield~localizedfield` (A is the brick name).

This way saving localized relation data to both bricks works.

2023-01-17 11:12 UTC, Corepex commented
@BlackbitDevs, thanks for your PR. This is a very interesting problem - thanks for fixing it.
I tested your changes and almost everything works as expected. 

I found one Issue:
If we update the logic, it is not possible to remove existing relations anymore. Obviously, you can click the "x" button, but this doesn't remove the (old formatted) relation from the DB. So the relation is still there if you reload.

AND even worse - you can "multi-assign" relations. 
If you check the DB (`object_relations_ID` table) you see a relation with the old format (e.g. `/objectbrick~aaaaaa//localizedfield~localizedfield`). You can try to remove this relation via the Backend UI (which doesn't work) and assign the same object (the class itself) again. Now you see the same relation as two entries in the `object_relations_ID` table. (one with the old format and the other one with the new format).

2023-01-19 12:26 UTC, BlackbitDevs commented
@Corepex You are right. What do you suggest? Imho we should "repair" the data in `object_relations_<class id>` table. I would suggest to write a migration which queries all items of `object_relations_*` tables `WHERE ownertype='localizedfield' AND ownername LIKE 'objectbrick~%'`. Then the object gets loaded via `src_id`, we call the getter for the object brick container field (comes from `ownername`). So we have the `\Pimcore\Model\DataObject\Objectbrick`. From this we call `getItems()` to get an array of `Pimcore\Model\DataObject\Objectbrick\Data\AbstractData` objects. And for those we call the `save()` method.

Alternative:
Query all items of `object_relations_*` tables `WHERE ownertype='localizedfield' AND ownername LIKE 'objectbrick~%'`. Get the class name of the object of `src_id`. With this class and the object brick container field name (via `ownername`), load the `\Pimcore\Model\DataObject\Product\ContainerField` class. From this we get the allowed bricks via `getBrickGetters()`. Then we loop through those allowed brick types, load their definitions, load `getLocalizedfields()`of this `Localizedfields` object try to load `getFieldDefinition(<fieldname from object_relations_* table>)`. If it exists (and is a relation field), we have found the object brick and can update all entries of `object_relations_<class id>` for this field.
This will be faster but is has the disadvantage that we may assign a brick which is actually not assigned to the object. So this will not work I think...

WDYT about the first method?

2023-01-23 15:55 UTC, Corepex commented
@BlackbitDevs, I would go for the first solution. Please keep in mind that calling `save()` isn't enough. You also have to delete the old relation from the `objects_relations_<class_id>` - otherwise it would have the same effect as clicking the save button in the backend UI.

It would also be nice if you could implement a test for that scenario.

2023-02-08 13:28 UTC, Corepex commented
@BlackbitDevs friendly reminder ⏰ 🍭

2023-02-20 08:36 UTC, Corepex commented
@BlackbitDevs friendly reminder ⏰

2023-03-17 09:32 UTC, Corepex commented
@BlackbitDevs final reminder. ⏰  
Please respond latest by 24.03 - otherwise, I will close the ticket due to inactivity.

2023-03-20 06:19 UTC, BlackbitDevs commented
@Corepex What do you think of supporting me? I have fixed a bug in your product and you put pressure on me and prefer to keep the bug instead of working together to fix it?

2023-03-20 13:36 UTC, BlackbitDevs commented
@Corepex I added the migration.

2023-03-31 09:28 UTC, fashxp requested changes

2023-03-31 09:28 UTC, fashxp commented on bundles/CoreBundle/Migrations/Version20230320131322.php
> +                                $objectBrick->markFieldDirty('testRelation');
hardcoded fieldname?

2023-03-31 09:28 UTC, fashxp commented on bundles/CoreBundle/Migrations/Version20230320131322.php
> +        $this->up($schema);
really?

2023-03-31 09:28 UTC, fashxp commented on bundles/CoreBundle/Migrations/Version20230320131322.php
> +                                $localizedFields->markFieldDirty('testRelation');
hardcoded fieldname?

2023-04-11 05:56 UTC, BlackbitDevs commented on bundles/CoreBundle/Migrations/Version20230320131322.php
> +                                $objectBrick->markFieldDirty('testRelation');
Fixed.

2023-04-11 05:57 UTC, BlackbitDevs commented on bundles/CoreBundle/Migrations/Version20230320131322.php
> +                                $localizedFields->markFieldDirty('testRelation');
Fixed.

2023-04-11 06:00 UTC, BlackbitDevs commented on bundles/CoreBundle/Migrations/Version20230320131322.php
> +        $this->up($schema);
Yes because this migration applies the saving logic for localized object brick relation fields - so whatever logic this is, will get used. It is similar to migrations like https://github.com/pimcore/pimcore/blob/a29a7a3c24d85e97d97417dad973b622dda5a582/bundles/CoreBundle/src/Migrations/Version20220318101020.php#L31-L51

Or do you prefer to extract the migration logic to a private method?

2023-05-09 08:56 UTC, merged

2023-05-09 08:57 UTC, Corepex commented
@BlackbitDevs, thanks for adding such a nice improvement. 🍭 
It was a long way, but now it is finally a part of Pimcore. 🥳