14340 make bundle migrations idempotent
pimcore/pimcore pull request #14342
Opened 2023-02-15 12:41 UTC by mattamon

## Changes in this pull request  
Resolves #14340 

## Additional info  
Removing the settings store setting in down method

2023-02-22 15:03 UTC, kingjia90 requested changes
The changes looks fine, but there are some inconsistencies of the merged migrations that may require some further changes.

2023-02-22 15:03 UTC, kingjia90 commented on bundles/CoreBundle/src/Migrations/Version20221228101109.php
> +        if (SettingsStore::get('BUNDLE_INSTALLED__Pimcore\\Bundle\\CustomReportsBundle\\PimcoreCustomReportsBundle', 'pimcore')) {
the `up` here also misses the `get` to check if is already in the settingstore

2023-02-22 15:03 UTC, kingjia90 commented on bundles/CoreBundle/src/Migrations/Version20221228101109.php
>          $this->write(sprintf('Please deactivate the %s manually in config/bundles.php', PimcoreCustomReportsBundle::class));
This could be a nice-to-have in every bundle migraton

2023-02-22 15:03 UTC, kingjia90 commented on bundles/CoreBundle/src/Migrations/Version20221215071650.php
> +        if (SettingsStore::get('BUNDLE_INSTALLED__Pimcore\\Bundle\\GlossaryBundle\\PimcoreGlossaryBundle', 'pimcore')) {
here too

2023-02-22 15:03 UTC, kingjia90 commented on bundles/CoreBundle/src/Migrations/Version20230120111111.php
> +        if (SettingsStore::get('BUNDLE_INSTALLED__Pimcore\\Bundle\\ApplicationLoggerBundle\\PimcoreApplicationLoggerBundle', 'pimcore')) {
this `up` also

2023-02-22 20:36 UTC, kingjia90 commented
Thank you for fixing all these!

Just noticed some other problems, unrelated to this PR. 

- [ ] ApplicationLogger: missing [permission category](https://github.com/pimcore/pimcore/blob/1e9f6135c0d112f0ae4cb7fc247a12d778847b32/bundles/ApplicationLoggerBundle/src/Installer.php#L80-L84) change + if valid, migration should also update the category
- [ ] CustomReports: missing [permission category](https://github.com/pimcore/pimcore/blob/1e9f6135c0d112f0ae4cb7fc247a12d778847b32/bundles/CustomReportsBundle/src/Installer.php#L44-L49)+ if valid, migration should also update the category
- [ ] FileExplorer: missing migration for [permission category ](https://github.com/pimcore/pimcore/blob/1e9f6135c0d112f0ae4cb7fc247a12d778847b32/bundles/FileExplorerBundle/src/Installer.php#L47)
- [ ] GlossaryBundle: same
- [ ] Google Marketing: same
- [ ] Personalization: same
- [ ] Seo: same
- [ ] StaticRoute: same

at first glance, either the other squad didn't know about the permission category change or they decided that it should stay in the core permissions, but would appreciate if this could be added in this PR

2023-02-23 08:05 UTC, mattamon commented
> Thank you for fixing all that!
> 
> Just noticed some other problems, unrelated to this PR's change.
> 
>     * [x]  ApplicationLogger: missing [permission category](https://github.com/pimcore/pimcore/blob/1e9f6135c0d112f0ae4cb7fc247a12d778847b32/bundles/ApplicationLoggerBundle/src/Installer.php#L80-L84) change + if valid, migration should also update the category
> 
>     * [x]  CustomReports: missing [permission category](https://github.com/pimcore/pimcore/blob/1e9f6135c0d112f0ae4cb7fc247a12d778847b32/bundles/CustomReportsBundle/src/Installer.php#L44-L49)+ if valid, migration should also update the category
> 
>     * [x]  FileExplorer: missing migration for [permission category ](https://github.com/pimcore/pimcore/blob/1e9f6135c0d112f0ae4cb7fc247a12d778847b32/bundles/FileExplorerBundle/src/Installer.php#L47)
> 
>     * [x]  GlossaryBundle: same
> 
>     * [x]  Google Marketing: same
> 
>     * [x]  Personalization: same
> 
>     * [x]  Seo: same
> 
>     * [x]  StaticRoute: same
> 
> 
> at first glance, il could be that the other squad didn't know about the permission category change or they decided that it should stay in the core permissions, but if it's a valid input, i would appreciate if these change could be added to this "cross-bundle" PR

It is a totally valid input and I added the Permission Category where I could! 
Google Marketing -> there is a new permission like with XLIFF
FileExplorer -> there is no migration for this Bundle, we decided to not install this per default.

ApplicationLogger and CustomReports I added the category to the installer.

SimpleBackendSearch -> there is no permission for this one, and also no migration.

2023-02-24 07:56 UTC, merged