Support language-specific transliteration
pimcore/pimcore pull request #14354
Opened 2023-02-16 07:50 UTC by BlackbitDevs

https://github.com/pimcore/pimcore/blob/8d9b9cf0fd1ba65ccf7485eb0be0547493ff267f/lib/Tool/Transliteration.php#L32-L38 pretends to support language-specific transliteration but in fact `$language` does not get used at all.

Before:
`Transliteration::toASCII('schön', 'de')` returns `schon`

After:
`Transliteration::toASCII('schön', 'de')` returns `schoen`

2023-02-16 10:54 UTC, brusch commented
Using ICU 67.1-7 it seems that your approach only covers `de`. 
If you look at `transliterator_list_ids()` you will see that there's only `de-ASCII` but no further languages with the `-ASCII` suffix, so I'm not sure if this is really generic enough ...

2023-02-16 12:34 UTC, BlackbitDevs commented
Better support `de` than not ;-)
And in case there are new rules added to ICU, it will automatically work in future. 

Am not sure how to support other languages, do you have any insights into ICU rules and how to apply them for ASCII conversion?

2023-02-16 12:37 UTC, BlackbitDevs commented
Alternatively we could also use https://github.com/Behat/Transliterator for transliteration. 
How do URL slugs implement this currently?

2023-02-16 13:27 UTC, brusch commented
@BlackbitDevs 

> Am not sure how to support other languages, do you have any insights into ICU rules and how to apply them for ASCII conversion?

To be honest, not really, but maybe we could implement a fallback, then transliterates to `Latin` first and then to `ASCII`, I guess that should be possible 🤔

2023-02-16 13:30 UTC, brusch commented
Regarding [Behat/Transliterator](https://github.com/Behat/Transliterator) : we had that before (not exactly that package, but I think same origin 😊 ) 
See: https://github.com/pimcore/pimcore/tree/6.9/lib/Tool/Transliteration/Data

It has other drawbacks, I'd prefer to stay on ICU data to be honest.

2023-02-17 07:24 UTC, BlackbitDevs commented
> but maybe we could implement a fallback, then transliterates to Latin first and then to ASCII

Isn't this exactly what we currently have?

Just tried this. But to me it does not make a difference. Do you mean this way?
`transliterator_transliterate('Any-Latin; Latin-ASCII; [^\u001F-\u007f] remove', $value);`
The ICU rule is formatted as <source language>-<target language>. So in this case it converts any characters to latin characters and afterwards latin to ASCII.

I see that you already discussed about this in https://github.com/pimcore/pimcore/issues/3175#issuecomment-413777442 - to me it is not clear why we don't support `<target language>-ASCII` if available and otherwise fall back to current behaviour.

2023-02-21 11:19 UTC, brusch commented
@BlackbitDevs you're right, I'm fine with it, but as it is an improvement I'd target it for `11.x`, can you rebase it? 
Thanks in advance!

2023-02-21 11:19 UTC, brusch requested changes

2023-02-21 11:19 UTC, brusch commented on lib/Tool/Transliteration.php
>          $value = trim($value);
```suggestion
```

I'd remove that, to be consistent and I don't see any benefit of it ...

2023-02-21 11:39 UTC, BlackbitDevs commented
@brusch I rebased to `11.x`

2023-03-23 10:14 UTC, merged