Improvement: Adds PRE_COPY event to the copy-contents-action
pimcore/pimcore pull request #14402
Opened 2023-02-20 14:43 UTC by SahinU88

## Changes in this pull request  

Resolves #14397

## Additional info  

In the issue-ticket is more details available, but in general the copy-contents-action ("Paste > Copy contents only here") action is not dispatching any event. This pull-request introduces the same event as in the other copy-actions (paste) so we can have an event-listener for that action.

If possible this would also be an idea for earlier versions. I think it should be rather easy to integrate.

If I am missing something in the code, I am happy to add or extend it.

Thanks!

2023-02-20 14:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/pimcore/pimcore?pullRequest=14402) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/pimcore/pimcore?pullRequest=14402) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/pimcore/pimcore?pullRequest=14402) it.</sub>

2023-02-21 08:07 UTC, SahinU88 commented
I've added the same functionality to the data-object and asset service aswell.

2023-02-21 08:32 UTC, brusch requested changes

2023-02-21 08:32 UTC, brusch commented on models/DataObject/Service.php
> +
Isn't `$target = $event->getArgument('target_element');` missing here?

2023-02-21 10:42 UTC, SahinU88 commented on models/DataObject/Service.php
> +
Oh yes, you're right. Just updated the branch. Thanks for the hint!

2023-02-28 12:47 UTC, SahinU88 commented
@brusch just wanted to check in if something is missing for the pull-request or I can help out with to finish the pull-request.

Thank you in advance!

2023-02-28 14:06 UTC, brusch commented
@SahinU88 not really for now, but we've moved that to `11.1` milestone, because the features for `11.0` are already frozen 😊

2023-02-28 14:11 UTC, SahinU88 commented
ah thanks for the information. 👍 I saw on the roadmap that there is no date yet, but I will just see the updates there :) if anything comes up, please just let me know.

✌️

2023-07-27 11:11 UTC, merged

2023-07-27 11:11 UTC, robertSt7 commented
@SahinU88 Thanks a lot for you contribution :)