Adds some info to thumbnail configuration
pimcore/pimcore pull request #14445
Opened 2023-02-24 09:38 UTC by NiklasBr

I'm certain that, at a minimum, my description of `status_cache` is wrong here, but I don't fully understand it after reading the code. So it would be nice to have some short documentation here.

2023-02-24 10:16 UTC, jdreesen commented on bundles/CoreBundle/DependencyInjection/Configuration.php
>                                  ->defaultValue(40000000)
Maybe we can improve the formatting of the number a bit. I, at least, have trouble to tell how much it is without the underscores.

```suggestion
                                ->defaultValue(40_000_000)
```

2023-02-27 13:38 UTC, mattamon requested changes

2023-02-27 13:38 UTC, mattamon commented on bundles/CoreBundle/DependencyInjection/Configuration.php
> +                                        ->info("Store image metadata in a cache")
As far as I checked this is more about a general performance improvement.
https://github.com/pimcore/pimcore/pull/11702 

As brusch mentions in his first comment:
This improves the performance significantly when using (remote) object storage for website projects.

Does this enhance your understanding on the config?

2023-02-27 14:23 UTC, NiklasBr commented on bundles/CoreBundle/DependencyInjection/Configuration.php
> +                                        ->info("Store image metadata in a cache")
Think I got a better grasp of it, thanks @mattamon.

2023-02-27 15:00 UTC, mattamon approved these changes
LGTM, descriptions are helpful!

2023-03-01 09:57 UTC, merged