Return 404 if disabled format is requested
pimcore/pimcore pull request #14617
Opened 2023-03-09 20:18 UTC by aryaantony92

## Changes in this pull request  
Resolves #13525 

## Additional info

2023-03-14 12:30 UTC, kingjia90 requested changes
If the issue #13525 has `bc break` label and the PR is for 11.x, then would probably need some change in docs 
https://github.com/pimcore/pimcore/blob/b23b847c42a79fce4ed6905570283a04ae2b221f/doc/04_Assets/03_Working_with_Thumbnails/01_Image_Thumbnails.md?plain=1#L437-L440
and a mention in the upgrade notes.

Or is it a non breaking change that should go in 10.5.x?

2023-03-14 12:30 UTC, kingjia90 commented on bundles/CoreBundle/src/Controller/PublicServicesController.php
> +                        return new Response("HTTP/1.1 404 Not Found\nRequested thumbnail format is disabled from the config", 404);
```suggestion
                    return new Response("Requested thumbnail format is disabled", Response::HTTP_NOT_FOUND);

                foreach($thumbnailFormats as $autoFormat => $autoFormatConfig) {
                    if(!$autoFormatConfig['enabled'] && $requestedFileExtension == $autoFormat) {
                        return new Response("Requested thumbnail format is disabled from the config", Response::HTTP_NOT_FOUND);
```

2023-03-14 12:30 UTC, kingjia90 commented on bundles/CoreBundle/src/Controller/PublicServicesController.php
> +                        return new Response("HTTP/1.1 404 Not Found\nRequested thumbnail format is disabled from the config", 404);
or what about using `throw new NotFoundHttpException('Requested thumbnail format is disabled');`?

2023-03-14 12:30 UTC, kingjia90 commented on bundles/CoreBundle/src/Controller/PublicServicesController.php
> +            if(!in_array($requestedFileExtension, ['jpg', 'jpeg'])) {
what's the reason behind this exception for jpg file formats?

2023-03-14 12:30 UTC, kingjia90 commented on bundles/CoreBundle/src/Controller/PublicServicesController.php
> +                    if(!$autoFormatConfig['enabled'] && $requestedFileExtension == $autoFormat) {
```suggestion
                    if($requestedFileExtension == $autoFormat && !$autoFormatConfig['enabled']) {
```
imho by swapping order, is easier to read

2023-03-14 12:42 UTC, kingjia90 commented
Probably the code should throw expection and be moved under https://github.com/pimcore/pimcore/blob/b23b847c42a79fce4ed6905570283a04ae2b221f/models/Asset/Service.php#L579

So that protected asset would also work that way, see https://github.com/pimcore/pimcore/pull/14155

2023-03-14 16:04 UTC, aryaantony92 commented on bundles/CoreBundle/src/Controller/PublicServicesController.php
> +            if(!in_array($requestedFileExtension, ['jpg', 'jpeg'])) {
The reason I avoided the check for jpg file formats it jpg image thumbnails are generated and displayed in the <picture> tag even if jpg/jpeg is enabled

2023-03-23 10:18 UTC, kingjia90 approved these changes

2023-03-23 10:21 UTC, merged