[Bug] Fixed `LibreOffice::getText` method
pimcore/pimcore pull request #14630
Opened 2023-03-13 11:21 UTC by Corepex

## Error Description

It seems that the convert to txt (txt:Text) doesn't work properly ...
That effects certain command (e.g. `pimcore:search-backend-reindex`)

## Additional info  
fixed some logical issues in `LibreOffice::getText`.

2023-03-13 11:58 UTC, brusch requested changes

2023-03-13 11:58 UTC, brusch commented on lib/Document/Adapter/Ghostscript.php
> +            }
@Corepex I guess we should throw an exception here in case `$path` is still null.

2023-03-13 12:06 UTC, Corepex commented on lib/Document/Adapter/Ghostscript.php
> +            }
done https://github.com/pimcore/pimcore/pull/14630/commits/9b91edc67c6d2a7166acca2d862a88318bda9c9b (bzw. https://github.com/pimcore/pimcore/pull/14630/commits/9fe406802dce6ce44c9b83b2941fd2c5b8b06a14)

2023-03-14 13:44 UTC, mcop1 commented on lib/Document/Adapter/LibreOffice.php
> +                $path = $this->getPdf($asset);
`getPdf` method doesn´t return a `path`, but a `resource`. If the resource is passed to the parent´s getText method on line 190 an error will be thrown: 
![grafik](https://user-images.githubusercontent.com/89011527/225020426-f667c7f0-8df4-4b7a-8cc3-f65a76d40592.png)

2023-03-14 13:51 UTC, mcop1 commented on lib/Document/Adapter/Ghostscript.php
> +                    throw new \Exception('Variable $path can\'t be null at this point.');
```suggestion
                    throw new \Exception('Could not get local file for asset with id ' . $asset->getId());
```
What do you think about adding a bit more detailed error message here?

2023-03-14 15:22 UTC, Corepex commented on lib/Document/Adapter/LibreOffice.php
> +                $path = $this->getPdf($asset);
thanks, seems like my cache didn't get cleared when using `bin/console c:c`. Fixed that within https://github.com/pimcore/pimcore/pull/14630/commits/ec8818703605158ee3d30fdfa3ee9f290550ecfd and https://github.com/pimcore/pimcore/pull/14630/commits/0d35077e610730078863ac0d1bed6610bb917c29

2023-03-14 15:28 UTC, merged