11877 feature migrate all logs to monolog
pimcore/pimcore pull request #14679
Opened 2023-03-16 12:01 UTC by robertSt7

resolves #11877

2023-03-21 11:41 UTC, dpfaffenbauer commented on bundles/AdminBundle/src/GDPR/DataProvider/PimcoreUsers.php
> +        $logDir = \Pimcore::getContainer()->getParameter('kernel.logs_dir');
dependency injection?!

2023-03-23 15:09 UTC, jdreesen commented on bundles/AdminBundle/src/GDPR/DataProvider/PimcoreUsers.php
> +        $logDir = $this->container->getParameter('kernel.logs_dir');
I think you should directly inject the parameter instead of the whole container just to get one parameter from it ;)

2023-03-28 05:52 UTC, dpfaffenbauer requested changes

2023-03-28 05:52 UTC, dpfaffenbauer commented on bundles/AdminBundle/src/GDPR/DataProvider/PimcoreUsers.php
> +        $this->container = $container;
Never ever inject the whole container, inject what you need!

2023-03-28 05:52 UTC, dpfaffenbauer commented on bundles/AdminBundle/src/GDPR/DataProvider/PimcoreUsers.php
> +        $this->container = $container;
just saw the follow up commit. you can ignore this.

2023-03-29 08:36 UTC, merged