[Object bricks] Add events when changing object brick definition
pimcore/pimcore pull request #15039
Opened 2023-04-25 16:13 UTC by BlackbitDevs

When a data object class gets created, saved or deleted there are events like `pimcore.class.preAdd`, `pimcore.class.postUpdate` or `pimcore.class.postDelete`, see https://github.com/pimcore/pimcore/blob/11.x/lib/Event/DataObjectClassDefinitionEvents.php. This PR adds similar events for object bricks: 
- `pimcore.objectbrick.preAdd`
- `pimcore.objectbrick.postAdd`
- `pimcore.objectbrick.preUpdate`
- `pimcore.objectbrick.postUpdate`
- `pimcore.objectbrick.preDelete`
- `pimcore.objectbrick.postDelete`

2023-04-25 22:07 UTC, jdreesen commented on lib/Event/ObjectbrickDefinitionEvents.php
> +    const POST_DELETE = 'pimcore.objectbrick.postDelete';
```suggestion
    /**
     * @Event("Pimcore\Event\Model\DataObject\ObjectbrickDefinitionEvent")
     *
     * @var string
     */
    const PRE_ADD = 'pimcore.objectbrick.preAdd';

    /**
     * @Event("Pimcore\Event\Model\DataObject\ObjectbrickDefinitionEvent")
     *
     * @var string
     */
    const POST_ADD = 'pimcore.objectbrick.postAdd';

    /**
     * @Event("Pimcore\Event\Model\DataObject\ObjectbrickDefinitionEvent")
     *
     * @var string
     */
    const PRE_UPDATE = 'pimcore.objectbrick.preUpdate';

    /**
     * @Event("Pimcore\Event\Model\DataObject\ObjectbrickDefinitionEvent")
     *
     * @var string
     */
    const POST_UPDATE = 'pimcore.objectbrick.postUpdate';

    /**
     * @Event("Pimcore\Event\Model\DataObject\ObjectbrickDefinitionEvent")
     *
     * @var string
     */
    const PRE_DELETE = 'pimcore.objectbrick.preDelete';

    /**
     * @Event("Pimcore\Event\Model\DataObject\ObjectbrickDefinitionEvent")
     *
     * @var string
     */
    const POST_DELETE = 'pimcore.objectbrick.postDelete';
```

2023-04-25 22:07 UTC, jdreesen commented on lib/Event/Model/DataObject/ObjectbrickDefinitionEvent.php
> +    }
```suggestion
    protected Definition $objectbrickDefinition;

    /**
     * @param Definition $objectbrickDefinition
     */
    public function __construct(Definition $objectbrickDefinition)
    {
        $this->objectbrickDefinition = $objectbrickDefinition;
    }

    /**
     * @return Definition
     */
    public function getObjectbrickDefinition(): Definition
    {
        return $this->objectbrickDefinition;
    }

    /**
     * @param Definition $objectbrickDefinition
     */
    public function setObjectbrickDefinition(Definition $objectbrickDefinition): void
    {
        $this->objectbrickDefinition = $objectbrickDefinition;
    }
```

2023-04-25 22:07 UTC, jdreesen commented on models/DataObject/Objectbrick/Definition.php
> +use Pimcore\Event\Model\DataObject\ClassDefinitionEvent;
Unused
```suggestion
```

2023-04-25 22:07 UTC, jdreesen commented on lib/Event/Model/DataObject/ObjectbrickDefinitionEvent.php
> +use Pimcore\Model\DataObject\ClassDefinition;
Unused
```suggestion
```

2023-04-26 05:46 UTC, BlackbitDevs commented
Thank you, @jdreesen!

2023-06-20 09:12 UTC, Corepex requested changes
LGTM

2023-06-20 09:12 UTC, Corepex commented on lib/Event/Model/DataObject/ObjectbrickDefinitionEvent.php
> +     */
```suggestion
```

2023-06-20 09:12 UTC, Corepex commented on lib/Event/Model/DataObject/ObjectbrickDefinitionEvent.php
> +     */
```suggestion
```

2023-06-20 09:12 UTC, Corepex commented on lib/Event/Model/DataObject/ObjectbrickDefinitionEvent.php
> +     */
```suggestion
```

2023-06-20 09:12 UTC, Corepex commented on lib/Event/Model/DataObject/ObjectbrickDefinitionEvent.php
> +
```suggestion
```

2023-09-21 14:07 UTC, aryaantony92 commented
@BlackbitDevs Thanks a lot!

2023-09-21 14:07 UTC, merged