[Docs] update system settings
pimcore/pimcore pull request #15063
Opened 2023-04-28 06:59 UTC by mcassier31

2023-05-09 09:11 UTC, lukmzig approved these changes

2023-05-10 08:00 UTC, fashxp requested changes

2023-05-10 08:00 UTC, fashxp commented on doc/18_Tools_and_Features/25_System_Settings.md
> +To switch from Symfony configuration to settings store for the first time, you need to copy the content of your `system_settings.yaml` file and convert it into JSON format.
well, that is not entirely correct ... you also could set read_target to symfony-config and write-target to settings-store ... and then just save the settings once. 

that might be easier that the procedure described here.

2023-05-10 14:05 UTC, fashxp approved these changes

2023-05-10 14:05 UTC, merged