[Docs] update Pimcore bundle generation
pimcore/pimcore pull request #15328
Opened 2023-06-05 07:40 UTC by mcassier31

- Move Encore section from "Pimcore Bundle" to "Loading Admin UI Assets"
- Remove enabling for Pimcore Generator

See https://github.com/pimcore/planning/issues/179

2023-06-06 05:49 UTC, martineiber approved these changes
LGTM.

2023-06-15 07:06 UTC, fashxp requested changes

2023-06-15 07:06 UTC, fashxp commented on doc/20_Extending_Pimcore/13_Bundle_Developers_Guide/13_Loading_Admin_UI_Assets.md
> +> This command accepts the path to `entrypoints.json`, file ending as string and returns an array with paths to the built files.
```suggestion
> This command accepts the path to `entrypoints.json` file ending as string and returns an array with paths to the built files.
```

2023-06-15 07:06 UTC, fashxp commented on doc/20_Extending_Pimcore/13_Bundle_Developers_Guide/05_Pimcore_Bundles/README.md
> -```php
should we not also move that code sample to `13_Loading_Admin_UI_Assets.md`?

2023-06-15 11:43 UTC, fashxp approved these changes

2023-06-15 11:43 UTC, merged