revert original logic from before breaking commit
pimcore/pimcore pull request #16405
Opened 2024-01-02 09:20 UTC by tecbird

Resolves #
https://github.com/pimcore/pimcore/issues/16397
https://github.com/pimcore/pimcore/pull/16398

2024-01-09 11:19 UTC, kingjia90 commented on models/DataObject/ClassDefinition/Data/AdvancedManyToManyObjectRelation.php
> +            // fix problem made by https://github.com/pimcore/pimcore/pull/13474
```suggestion
```

2024-01-09 11:31 UTC, kingjia90 requested changes
LGTM, just need to apply to 

https://github.com/pimcore/pimcore/blob/03bf254b6ff3df6c9a6668208623026a6fe3e49b/models/DataObject/ClassDefinition/Data/AdvancedManyToManyRelation.php#L902-L908
as well, but in there, instead of `ObjectMetadata`, it should be `ElementMetadata`

2024-01-12 07:31 UTC, blankse commented
@tecbird @kingjia90 I created a alternative PR with more type hint corrections: https://github.com/pimcore/pimcore/pull/16458

2024-01-15 09:50 UTC, kingjia90 commented
Closing in favor of https://github.com/pimcore/pimcore/pull/16458
Thank you again for proving a PR

2024-01-15 09:50 UTC, closed without merging