[Data Objects] Password : Deprecate support for algorithms other than password_hash
pimcore/pimcore pull request #16736
Opened 2024-03-05 12:28 UTC by kingjia90

## Changes in this pull request  
Resolves https://github.com/pimcore/pimcore/issues/16294

## Additional info

2024-03-11 11:08 UTC, brusch requested changes

2024-03-11 11:08 UTC, brusch commented on models/DataObject/ClassDefinition/Data/Password.php
>      public function setAlgorithm(string $algorithm): void
@kingjia90 Should we `@deprecate` all obsolete properties and methods as well, even if they are internal? Just that we don't forget to remove them later ...

2024-03-11 11:17 UTC, kingjia90 commented on models/DataObject/ClassDefinition/Data/Password.php
>      public function setAlgorithm(string $algorithm): void
yes, nice idea, thank you

2024-03-12 08:40 UTC, brusch commented
@kingjia90 I'd even deprecate `get/setAlgorithm` incl. the property as we don't need it anymore in future. Pushed it already to your branch.

2024-03-12 14:13 UTC, merged