[Bug, EC]: Fix Sorter of classification store group collection
pimcore/pimcore pull request #16769
Opened 2024-03-12 15:19 UTC by kingjia90

## Changes in this pull request  
Resolves https://github.com/pimcore/pimcore/issues/16723
Re-opening from https://github.com/pimcore/pimcore/pull/16753

## Additional info
When adding a group collection and save without any data in any of the fields,  there would de no record in `object_classification_store_xyz` due to `$items` being empty https://github.com/pimcore/pimcore/blob/cbc427c6b615e9dd1e9cbec31e878dec37de91ac/models/DataObject/Classificationstore/Dao.php#L89 won't perform any upsert https://github.com/pimcore/pimcore/blob/cbc427c6b615e9dd1e9cbec31e878dec37de91ac/models/DataObject/Classificationstore/Dao.php#L132 causing later on to lose the information that these groups belong to a collection (since it's not stored anywhere else other than [here](https://github.com/pimcore/pimcore/blob/4da5b84117965399f87d6151b765f25cddb01a6c/models/DataObject/Classificationstore/Dao.php#L101)).

WIth this PR, instead of first removing everything and upsert later, it's inverted, first upsert and keep the info needed and then delete the rest. 
Another change is that table `object_classification_store_xyz` would store empty placeholder rows with type as `<system>` that get removed(with $systemRowToDelete, not replace because couldn't find keyId to pass and it's used in the primary key) once the real data is filled.

## Tips for reviewers
With demo dump, go to classification store, get `ProductAttributes` first Collections name `Size`, add a `Sorter` value of `100` to `Dimensions`. As long as it appears as second group on save/load, then it's working.
Keep an eye on the `object_classification_store_xyz` table on each save before and after PR.

## Draft
Need to double-check inheritance (seems fine so far) and if there are any deadlocks or any performance degradation by choosing this approach. One downside is that would be filled by empty `<system>` placeholder mentioned above but seems the only way to remember which collection these groups belong to.

## Doubt
Another issue if one delete one group (x icon on object editmode) after importing the group collection, does it means that the remaining groups should be now seen as independent (remove the collectionId from them)? At the moment, it somehow re-adds in editmode, maybe need a follow-up or fix for this.

## Alternatives
Probably adding a column to `object_classificationstore_groups_xyz` would also work, but then would need more refactoring, as currently seem working all around the column in `object_classification_store_xyz`

2024-04-11 09:34 UTC, micru commented
Any news on this? We experience the same issue and our customer needs it urgently

2024-04-11 09:46 UTC, fashxp commented
you could help and speed things up by testing and improving current approach.

2024-04-22 15:03 UTC, fashxp requested changes
I found a problem in combination with inheritance: 

- add a collection with two groups A and B to a parent object and save --> it creates two empty rows into classification_store_data table :heavy_check_mark: 
- open child object, overwrite one field in group B and save --> it creates an empty row into classification_store_data table for group A too :heavy_multiplication_x: 
- open parent object and delete group A and save, reload child object --> it still will show group A as inherited (until you delete it manually for the child object too) :heavy_multiplication_x:

2024-04-23 09:11 UTC, fashxp approved these changes

2024-04-23 11:19 UTC, merged