Add completion for `pimcore:bundle:(un)install`
pimcore/pimcore pull request #16932
Opened 2024-04-13 08:42 UTC by matthiashamacher

## Changes in this pull request  
Startet as idea to implement completion for the `pimcore:bundle:(un)install` commands ended with refactoring / updating all `pimcore:bundle:*` commands and related classes:

- Added completion for bundle argument for `pimcore:bundle:(un)install`
- Refactored `pimcore:bundle:*` to use `AsCommand`-Attribute
- Remove unused functions: 
  - `AbstractBundleCommand::configureDescriptionAndHelp`
  - `AbstractBundleCommand::buildName` -> no longer needed as names are set via `AsCommand` directly
- Remove unnecessary if-else constructs in favor of early returns
- Use `Command::SUCCESS` and `Command::FAILURE` instead of ints
- Add `readonly` to properties
- Remove `$e` from exceptions when unused
- Use  `$this->io->table()` instead of `new Table()` for simplification
- Some more refactoring

2024-09-11 09:35 UTC, mattamon commented
@matthiashamacher thank you for your patience. Could you please resolve the conflicts first so we can have a better look at it. Thank you!

2024-10-04 06:53 UTC, mattamon commented
> @matthiashamacher thank you for your patience. Could you please resolve the conflicts first so we can have a better look at it. Thank you!

I took the liberty to resolve the conflicts myself, so I can properly test it.

2024-12-13 07:37 UTC, mattamon commented
@matthiashamacher we should also update the docs since the auto-complete features does not work out of the box https://symfony.com/doc/current/console.html#console-completion

Did you also try this in a docker-container setup?

2025-08-08 09:09 UTC, kingjia90 requested changes

2025-08-08 09:09 UTC, kingjia90 commented on bundles/CoreBundle/src/Command/Bundle/Helper/PostStateChange.php
> + * @TODO: Make class readonly and remove readonly from properties when PHP 8.1 support is dropped
This PR would be merged in `12.x` and there we already [dropped PHP 8.1](https://github.com/pimcore/pimcore/pull/17982), could be this TODO be done already?
TIA

2025-08-18 08:48 UTC, kingjia90 requested changes
Thank you for your PR!
Codewise LGTM, just some small tweaks, but i can't reproduce/use it locally (maybe some limitation in docker container?), i face this error 
<img width="925" height="205" alt="image" src="https://github.com/user-attachments/assets/01d02057-62e0-4069-9531-ecd81f6e57d3" />
and should be on bash
<img width="925" height="205" alt="image" src="https://github.com/user-attachments/assets/fc59eb2f-ab67-4d67-b5a7-a8e843e5dac7" />

2025-08-18 08:48 UTC, kingjia90 commented on bundles/CoreBundle/src/Command/Bundle/ListCommand.php
> +            'Uninstallable',
```suggestion
            $input->getOption('json') ? 'Installable' : 'I?',
            $input->getOption('json') ? 'Uninstallable' : 'UI?',
```

I feel there it was meant to have a narrower column but the `hasOption` was not used as intended, it's always truthy as if it checks if the option is an available one, by replacing with getOption would appear as

<img width="1037" height="335" alt="image" src="https://github.com/user-attachments/assets/1d3e6aff-75da-4869-9255-2564f2e87e6b" />

2026-08-05 09:41 UTC, kingjia90 commented on bundles/CoreBundle/src/Command/Bundle/Helper/PostStateChange.php
> + * @TODO: Make class readonly and remove readonly from properties when PHP 8.1 support is dropped
Done in c4aa5b3ac19 — the class is now `readonly` and the TODO is gone.

2026-08-05 09:41 UTC, kingjia90 commented on bundles/CoreBundle/src/Command/Bundle/ListCommand.php
> +            'Uninstallable',
Applied in 08230d27509 — table output uses the narrow `I?`/`UI?` headers again (JSON keeps the full names) and the legend is back, without the never-existing `UP?`.

2026-08-05 09:53 UTC, kingjia90 commented on bundles/CoreBundle/src/Command/Bundle/AbstractBundleCommand.php
> +    protected function completeBundleArgument(CompletionInput $input, CompletionSuggestions $suggestions): void
Added `tests/Unit/CoreBundle/Command/Bundle/BundleCommandCompletionTest.php` in 280a00c33c2 — covers bundle-name suggestions for the `bundle` argument of both commands, and asserts nothing leaks into option or post-argument completion.

2026-08-05 10:18 UTC, kingjia90 approved these changes
All requested changes are applied and verified:
- `PostStateChange` is a readonly class now (PHP 8.1 TODO resolved)
- narrow `I?`/`UI?` table headers with legend are back, JSON keeps full key names
- completion tested locally (bash): active bundle names are suggested for the `bundle` argument of both commands, with regression tests in `BundleCommandCompletionTest`
- the docker error from my earlier review was environmental — the `bash-completion` package was missing in the container (`_get_comp_words_by_ref: command not found`); works fine once installed, now also covered in the docs
- table style is scoped to `pimcore:bundle:list` so other commands' output is unchanged

Copilot review is clean and CI is green.

2026-08-05 10:50 UTC, merged