[Documentation] [Bugix] Tinymce documentation fix
pimcore/pimcore pull request #17064
Opened 2024-05-16 13:17 UTC by questionmark78

The documentation on the Tinymce Bundle states that global config settings can be put in a editmode.js of a custom bundle. But this is not true for the wysiwyg fields in the data objects, these settings should go inside the startup.js of the custom bundle. 

In this PR the documentation is improved/corrected on this point.

2024-07-05 06:24 UTC, robertSt7 requested changes

2024-07-05 06:24 UTC, robertSt7 commented on bundles/TinymceBundle/README.md
> +var YourTinymceEditorConfigBundlePlugin = new pimcore.plugin.YourTinymceEditorConfigBundle();
```suggestion
const YourTinymceEditorConfigBundlePlugin = new pimcore.plugin.YourTinymceEditorConfigBundle();    
```

2024-07-07 08:24 UTC, questionmark78 commented
I have read the CLA Document and I hereby sign the CLA

2024-07-12 07:40 UTC, brusch approved these changes

2024-07-12 07:41 UTC, merged

2024-07-12 07:41 UTC, brusch commented
Thank you very much! 👍