Fix: #17582 Tests to confirm the proper functionality of pimcore_placeholder with twig/twig 3.14
pimcore/pimcore pull request #17593
Opened 2024-09-11 10:13 UTC by michalananapps

## Changes in this pull request  
Resolves #17582

## Additional info
Some tests have been added to confirm the proper functionality of pimcore_placeholder with twig/twig 3.14

2024-09-11 10:15 UTC, michalananapps commented
recheck

2024-09-11 15:02 UTC, kingjia90 commented
@michalananapps Thank you for your PR!
The CLA should be rechecked after posting a comment with only this phrase 
`I have read the CLA Document and I hereby sign the CLA`

2024-09-11 16:44 UTC, michalananapps commented
I have read the CLA Document and I hereby sign the CLA

2024-09-18 15:04 UTC, markus-moser commented
I can confirm that the current twig version seems to fix our problems with the output buffering. We still need to test all the cases in detail but from what I can see at the moment it looks good. 

Unfortunately the rybakit/twig-deferred-extension is still broken.

2024-09-25 10:22 UTC, kingjia90 requested changes
Thank you for tests!
Overall LGTM, just the composer changes need to be reverted, because it has to be possible to install `twig` < `3.9.0`, in case some project need to be using the `twig-deferred-extension`.

2024-09-25 10:22 UTC, kingjia90 commented on composer.json
> +    "twig/twig": "^3.14",
```suggestion
    "twig/extra-bundle": "^3.4.0",
    "twig/string-extra": "^3.3.5",
    "twig/twig": "^3.3.9",
```

2024-09-25 10:22 UTC, kingjia90 commented on composer.json
> +    "thecodingmachine/safe": "<2.0"
```suggestion
    "thecodingmachine/safe": "<2.0",
    "twig/twig": ">=3.9.0 <3.14.0"
```

2024-09-26 15:48 UTC, merged