Improvement: check validity for (Multi)Select before setting values
pimcore/pimcore pull request #17742
Opened 2024-10-18 15:12 UTC by samynw

## Changes in this pull request

As described in issue #17343, when using the Pimcore API, any value can be set on a select or multiselect field. This improvement checks the validity before setting the data by matching the value against the allowed options.

If the given data is not allowed, a ValidationException will be thrown.

## Additional info

The validity check supports:
* configured options
* SelectOptions
* OptionProvider

Resolves: #17343

2024-10-18 15:13 UTC, samynw commented
I have read the CLA Document and I hereby sign the CLA

2024-10-23 13:21 UTC, blankse commented on models/DataObject/ClassDefinition/Data/Multiselect.php
> +        if (empty($this->getOptions())) {
We should avoid using empty here. See https://localheinz.com/articles/2023/05/10/avoiding-empty-in-php/
```suggestion
        if (!$this->getOptions()) {
```

2024-10-23 13:21 UTC, blankse commented on models/DataObject/ClassDefinition/Data/Multiselect.php
> +        return !empty($matches);
```suggestion
        return count($matches) > 0;
```

2024-10-23 13:21 UTC, blankse commented on models/DataObject/ClassDefinition/Data/Select.php
> +        if (empty($this->getOptions())) {
```suggestion
        if (!$this->getOptions()) {
```

2024-10-23 13:21 UTC, blankse commented on models/DataObject/ClassDefinition/Data/Select.php
> +        return !empty($matches);
```suggestion
        return count($matches) > 0;
```

2024-10-23 13:21 UTC, blankse commented on models/DataObject/ClassDefinition/Data/Multiselect.php
> +    public function isValidOption(mixed $data): bool
Can be private
```suggestion
    private function isValidOption(mixed $data): bool
```

2024-10-23 13:21 UTC, blankse commented on models/DataObject/ClassDefinition/Data/Select.php
> +    public function isValidOption(mixed $data): bool
```suggestion
    private function isValidOption(mixed $data): bool
```

2024-10-23 14:34 UTC, samynw commented on models/DataObject/ClassDefinition/Data/Multiselect.php
> +    public function isValidOption(mixed $data): bool
The public scope was added intentionally, to allow values to be checked as a stand-alone method. However, your point is definitely valid, as the `checkValidity()` method already fulfills that need. I'll accept your suggestion.

2025-04-22 05:58 UTC, blankse approved these changes

2025-08-12 15:01 UTC, kingjia90 requested changes
My concern from a bigger picture is that (feels like) the former behavior was kind of intended, at least for existing data: 

- Given A,B,C, if one picks A,B,C and save.
- Temporary remove C from available options.
- Try to save object again without any changes

Before PR, C would "disappear" from the UI list, but if one restores the option with the same name, then it would be there again as selected (because the value matches). No any blocks from saving.
After PR, C is not removable from UI perspective and the object is stuck forever (can't save, as it doesn't clear the invalid option and keeps throwing exception), until someone overwrite the set value via API.


Maybe we need to refactor to something more limited to API, of ex-novo objects (empty existing selection) and/or may need some more insights from @fashxp @brusch  first

2025-08-12 15:01 UTC, kingjia90 commented on models/DataObject/ClassDefinition/Data/Multiselect.php
> +        return count($matches) > 0;
```suggestion
            // If no options are defined yet, skip the validation
            if (!$this->getOptions()) {
                return;
            }

            foreach ($data as $value) {
                if (!$this->isValidOption($value)) {
                    throw new Model\Element\ValidationException(
                        sprintf("Invalid multiselect option '%s' on field [ %s ]", $value, $this->getName())
                    );
                }
            }
        }
    }

    /**
     * Validates if the provided data matches any of the available options.
     *
     */
    private function isValidOption(mixed $data): bool
    {
          $options = $this->getOptions();
          foreach ($options as $option) {
              if (($option['value'] ?? null) == $data) {
                  return true;
              }
          }
      
          return false;
```
So far LGTM, just wanted to add an input to move the validation skip outside the `foreach` loop and to simplify the valid option check. wdyt?

2025-08-14 08:13 UTC, brusch commented
@kingjia90 @samynw What do you guys think about making the behavior configurable? 
So an option in the config of the select data-types to enforce validity or not. 
This would have the benefit of being a non-breaking change, as we can keep the current behavior as the default, and would also cover the topic outlined by @kingjia90 above. 

WDYT?

2025-08-14 08:23 UTC, kingjia90 commented
> @kingjia90 @samynw What do you guys think about making the behavior configurable? So an option in the config of the select data-types to enforce validity or not. This would have the benefit of being a non-breaking change, as we can keep the current behavior as the default, and would also cover the topic outlined by @kingjia90 above.
> 
> WDYT?

Thank you @brusch for having a look and the feedback, to me it sounds good, a sort of strict mode that also takes care of the redundant/orphanized data (and remove the not visible data and in-existing options), configurable at a single data type field level

2025-08-28 10:50 UTC, kingjia90 commented
@samynw 🏓 Could you please have a look the latest feedbacks and apply the changes? Thank you in advance

2025-11-05 11:39 UTC, kingjia90 commented
Any updates? Please let me know if i should take over and apply the requested changes of making it configurable, TIA

2025-11-12 09:24 UTC, samynw commented
@kingjia90 Thank you for your feedback. You make a valid point and your example topic makes sense. I agree with you, and the suggestion of @brusch to make it configurable is definitely the best approach. 

However, I'm currently limited in availability to apply the suggested changes, so @kingjia90 feel free to take over if you are still up for it, that would be great!

2025-12-02 12:40 UTC, kingjia90 commented
Tests looks working fine 
<img width="541" height="134" alt="image" src="https://github.com/user-attachments/assets/854fa24d-0f36-424a-ae64-ff39c7cd5cc0" />
https://github.com/pimcore/pimcore/pull/17742/commits/f14a4775100eb59c7eb0a53f3da7e87d5643e8f1

2025-12-04 12:12 UTC, merged