[WIP] Introduce new block syntax
pimcore/pimcore pull request #17792
Opened 2024-11-04 10:18 UTC by martineiber

## Changes in this pull request  
Part of https://github.com/pimcore/pimcore/pull/17664

## Additional info

2024-11-04 10:26 UTC, jdreesen commented on doc/03_Documents/01_Editables/06_Block.md
> +| `manual`    | bool      | Forces the manual mode, which enables a complete custom HTML implementation for blocks, for example using `<table>` elements <br/> <b>Deprecated</b> Will be removed in Pim
```suggestion
| `manual`    | bool      | Forces the manual mode, which enables a complete custom HTML implementation for blocks, for example using `<table>` elements <br/> <b>Deprecated</b> Will be removed in Pimcore 12 use `endpimcoremanualblock` instead. |
```

2024-11-04 10:26 UTC, jdreesen commented on doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
> +- `pimcore_block` Twig extension is deprecated. Use `pimcoreblock` or `pimcoremanualblock`instead.
```suggestion
- `pimcore_block` Twig extension is deprecated. Use `pimcoreblock` or `pimcoremanualblock` instead.
```

2024-11-06 08:04 UTC, markus-moser commented on doc/03_Documents/01_Editables/06_Block.md
> +| `manual`    | bool      | Forces the manual mode, which enables a complete custom HTML implementation for blocks, for example using `<table>` elements <br/> <b>Deprecated</b> Will be removed in Pim
Should we change `endpimcoremanualblock` to `pimcoremanualblock` here?

2024-11-06 08:06 UTC, markus-moser commented on doc/03_Documents/01_Editables/06_Block.md
> +{% endpimcoreblock %}
Shouldn't this be `endpimcoremanualblock`?

2024-11-06 08:12 UTC, markus-moser requested changes
Please check the 2 comments in the docs, the rest LGTM :)

2024-11-06 12:29 UTC, NiklasBr reviewed
I suppose this is just a language quirk, but Manuel -> Manual

2024-11-06 12:29 UTC, NiklasBr commented on lib/Twig/Node/ManuelBlockNode.php
> +final class ManuelBlockNode extends Node
```suggestion
final class ManualBlockNode extends Node
```

Probably need to rename file also.

2024-11-06 12:29 UTC, NiklasBr commented on lib/Twig/Options/BlockOptions.php
> +    private function getManuelAsString(): string
```suggestion
    private function getManualAsString(): string
```

2024-11-06 12:29 UTC, NiklasBr commented on lib/Twig/Options/BlockOptions.php
> +        $options .= "'manual' => " . $this->getManuelAsString() .',';
```suggestion
        $options .= "'manual' => " . $this->getManualAsString() .',';
```

2024-11-06 12:29 UTC, NiklasBr commented on lib/Twig/TokenParser/ManualBlockParser.php
> +use Pimcore\Twig\Node\ManuelBlockNode;
```suggestion
use Pimcore\Twig\Node\ManualBlockNode;
```

2024-11-06 12:29 UTC, NiklasBr commented on lib/Twig/TokenParser/ManualBlockParser.php
> +        return new ManuelBlockNode(
```suggestion
        return new ManualBlockNode(
```

2024-11-06 13:35 UTC, martineiber commented
> I suppose this is just a language quirk, but Manuel -> Manual

Good catch. Thank you :smiley:

2024-11-07 10:51 UTC, markus-moser approved these changes

2024-11-07 10:56 UTC, merged