Update PageSnippet to respect pretty url if site is using
pimcore/pimcore pull request #17809
Opened 2024-11-07 15:43 UTC by BlackbitDevs

This PR allows to use pretty url if document belongs to site.
Now pimcore doesn't use document pretty url if document belongs to site https://github.com/pimcore/pimcore/blob/11.x/models/Document/PageSnippet.php#L570

2025-04-16 09:20 UTC, kingjia90 requested changes
Thank you for your PR!

It seems it break the non-site pages, so suggesting these changes and then could be merged

2025-04-16 09:20 UTC, kingjia90 commented on models/Document/PageSnippet.php
> +        throw new Exception('No hostname available');
```suggestion
        return \Pimcore\Config::getSystemConfiguration('general')['domain']
            ?: \Pimcore\Tool::getHostname()
            ?: throw new Exception('No hostname available');
```

2025-04-16 09:20 UTC, kingjia90 commented on models/Document/PageSnippet.php
> +            $url .= preg_replace('@^'.$site->getRootPath().'/?@', '/', $this->getRealFullPath());
```suggestion
            if ($site instanceof Model\Site){
                $url .= preg_replace('@^'.$site->getRootPath().'/?@', '/', $this->getRealFullPath());
            } else {
                $url .= $this->getFullPath();
            }
```

2025-04-16 09:25 UTC, kingjia90 commented on models/Document/PageSnippet.php
>              $url .= $this->getPrettyUrl();
mhh.. wait, how it works if we are not changing under this

2025-04-30 07:32 UTC, BlackbitDevs commented
Hi @kingjia90,
have applied your suggested changes and merged latest 12.x branch.

2025-04-30 09:33 UTC, merged