[DataObject] Fix block inside localized field
pimcore/pimcore pull request #7000
Opened 2020-08-26 09:28 UTC by dvesh3

## Changes in this pull request  
Resolves #6976

## Additional info

2020-08-26 09:53 UTC, weisswurstkanone approved these changes

2020-08-26 09:54 UTC, weisswurstkanone requested changes
unit tests

2020-08-26 10:41 UTC, dvesh3 commented
> unit tests

@weisswurstkanone reverted

2020-08-26 11:43 UTC, weisswurstkanone commented
@dvesh3  still failing

2020-08-27 14:10 UTC, jdreesen commented on models/DataObject/Data/BlockElement.php
> +            }
Why do you need an anonymous class here? Shouldn't this be sufficient?

```suggestion
            new TypeMatcher(ElementInterface::class)
```

2020-08-28 08:16 UTC, weisswurstkanone commented
We will come up with a generic approach.

Discussion points:
* https://github.com/pimcore/pimcore/pull/5799
* https://github.com/pimcore/pimcore/pull/6236

2020-08-28 08:16 UTC, closed without merging