Pimcore requires doctrine/dbal ^2.11.0 and php ^7.3
pimcore/pimcore pull request #7453
Opened 2020-11-03 14:38 UTC by blankse

The PR https://github.com/pimcore/pimcore/pull/7327 use \Doctrine\DBAL\Exception which is first created in doctrine/dbal 2.11.0.
doctrine/dbal 2.11.0 requires php ^7.3

2020-11-03 14:41 UTC, brusch commented
Just wanted to comment that Travis needs to be changed 😉 Thanks for updating the PR.

2020-11-03 14:44 UTC, brusch commented
Related to #7410
@blankse can you maybe also fix the deprecations in this PR?

2020-11-03 14:54 UTC, jdreesen commented
`doctrine/dbal v2.11` has many more deprecations that should also be fixed: https://github.com/doctrine/dbal/blob/2.12.x/UPGRADE.md#upgrade-to-211

2020-11-04 13:05 UTC, blankse commented
@brusch @jdreesen I fixed many 2.11 deprecations.

There are deprecations in QueryBuilder and a deprecation with the getParams() (is internal now).
QueryBuilder is also deprecated, so I ignore it for now.
For getParams exists no alternative. We should load it direct from the settings?

But we can leave it at that for now, or?

2020-11-04 13:09 UTC, brusch commented
@blankse nice, thanks a lot! 
`QueryBuilder`  👍
`getParams()` yep, we have to get the info then from the settings - are you updating the PR? 😊

2020-11-04 13:11 UTC, brusch commented
@blankse regarding `>=` PHP 7.3 we should update this in the docs as well: 
https://github.com/pimcore/pimcore/blob/ae7b62cc4a0ade1bac5ad70d720187215344f827/doc/Development_Documentation/23_Installation_and_Upgrade/01_System_Requirements.md#L12

2020-11-04 14:08 UTC, blankse commented
@brusch I looked in the container. There are no symfony parameter for the db settings. They are only set to the Connection cunstructur.

2020-11-04 14:15 UTC, brusch commented
@blankse hm, too bad, then we need to put it on the container as a parameter I guess, probably here is a good place for that: 
https://github.com/pimcore/pimcore/blob/9af9958fbcfb9e86406f8076212196a52b831b81/bundles/CoreBundle/DependencyInjection/PimcoreCoreExtension.php#L70
wdyt?

2020-11-04 14:21 UTC, blankse commented
@brusch From where do you want get the settings in the PimcoreCoreExtension? The config variable have only the settings from the pimcore configuration tree.

The db settings are in the doctrine configuration tree.

2020-11-04 14:23 UTC, brusch commented
@blankse 🤦‍♂️ you're right, sorry 😊

2020-11-04 15:04 UTC, brusch commented
I think using the `@internal` tagged `getParams()` is fine for now, if Doctrine changes something there in the future we can always add our own getter to `\Pimcore\Db\PimcoreExtensionsTrait`.

2020-11-04 15:16 UTC, blankse commented
@brusch I agree with you

2020-11-04 15:26 UTC, brusch requested changes
I think it's more generic if we use `\Doctrine\DBAL\Driver\Result` instead of `\Doctrine\DBAL\Driver\PDO\Statement` then `Mysqli` is still an option 😊

2020-11-04 15:26 UTC, brusch commented on lib/Db/PimcoreExtensionsTrait.php
> +use Doctrine\DBAL\Driver\PDO\Statement as PDOStatement;
```suggestion
use Doctrine\DBAL\Driver\Result;
```

2020-11-04 15:26 UTC, brusch commented on lib/Db/PimcoreExtensionsTrait.php
> +        if ($stmt instanceof PDOStatement) {
```suggestion
        if ($stmt instanceof Result) {
```

2020-11-04 15:26 UTC, brusch commented on lib/Db/PimcoreExtensionsTrait.php
> +        if ($stmt instanceof PDOStatement) {
```suggestion
        if ($stmt instanceof Result) {
```

2020-11-04 15:26 UTC, brusch commented on lib/Targeting/Storage/DbStorage.php
> +use Doctrine\DBAL\Driver\PDO\Statement as PDOStatement;
```suggestion
use Doctrine\DBAL\Driver\Result;
```

2020-11-04 15:26 UTC, brusch commented on lib/Targeting/Storage/DbStorage.php
> +        if ($stmt instanceof PDOStatement) {
```suggestion
        if ($stmt instanceof Result) {
```

2020-11-04 15:26 UTC, brusch commented on lib/Targeting/Storage/DbStorage.php
> +        if ($stmt instanceof PDOStatement) {
```suggestion
        if ($stmt instanceof Result) {
```

2020-11-04 15:26 UTC, brusch commented on lib/Targeting/Storage/DbStorage.php
> +        if ($stmt instanceof PDOStatement) {
```suggestion
        if ($stmt instanceof Result) {
```

2020-11-04 15:26 UTC, brusch commented on lib/Targeting/Storage/DbStorage.php
> +        if ($stmt instanceof PDOStatement) {
```suggestion
        if ($stmt instanceof Result) {
```

2020-11-04 15:39 UTC, merged