[DataObject] Classificationstore + QuantityValue not properly restored
pimcore/pimcore pull request #8116
Opened 2021-02-08 12:33 UTC by weisswurstkanone

resolves #8114

2021-02-09 09:21 UTC, dvesh3 requested changes
Data not saved for direct inputQuantity fields on object class as generated tables unit column is bigint and it should be varchar
![image](https://user-images.githubusercontent.com/5137917/107342349-64107f80-6ac0-11eb-9ade-0150a1d58a44.png)

line: https://github.com/pimcore/pimcore/blob/48102717faaa6e0283644636457c9cdb77961c25/models/DataObject/ClassDefinition/Data/QuantityValue.php#L95

https://github.com/pimcore/pimcore/blob/48102717faaa6e0283644636457c9cdb77961c25/models/DataObject/ClassDefinition/Data/QuantityValue.php#L95

2021-02-09 09:26 UTC, dvesh3 requested changes
if InputQuantityValue field is inside Classificationstore, then on save it throws validation error..
![image](https://user-images.githubusercontent.com/5137917/107343040-3d067d80-6ac1-11eb-9453-e07c2109a4f1.png)

2021-02-09 15:38 UTC, weisswurstkanone commented
@dvesh3 unable to reproduce the validation error

2021-02-11 16:01 UTC, dvesh3 commented on bundles/CoreBundle/Migrations/Version20210211152319.php
> +            $class->generateClassFiles(false);
generating classes is not enough.....we need to up db tables as well for column type update

2021-02-11 16:01 UTC, dvesh3 approved these changes

2021-02-11 16:05 UTC, dvesh3 requested changes
Update migration

2021-02-11 16:10 UTC, dvesh3 commented on bundles/CoreBundle/Migrations/Version20210211152319.php
> +            $class->generateClassFiles(false);
Even calling `$class->save()` in migration has no impact on existing classes.

2021-02-12 10:11 UTC, dvesh3 approved these changes

2021-02-12 10:14 UTC, merged