Fixes deleting a Website Setting not clearing it from cache
pimcore/pimcore pull request #8451
Opened 2021-03-15 11:57 UTC by NiklasBr

If a setting is first deleted:

```php
$settingObject->delete();
```

It was then still available to the process and returned via 

```php
WebsiteSetting::getByName()
```

Which should not have happened. This overrides the Dao to to resolve the issue.

2021-03-15 12:08 UTC, brusch commented
@NiklasBr can you please check PhpStan? Thanks a lot!

2021-03-15 12:10 UTC, NiklasBr commented
Yes, found the issue

2021-03-15 13:08 UTC, brusch requested changes

2021-03-15 13:08 UTC, brusch commented on models/WebsiteSetting.php
> +        $nameCacheKey = $this->getName() . '~~~' . $this->getSiteId() . '~~~' . $this->getLanguage();
I think it would be good to have this in a `protected static function`, then we can share it with `getByName`.

2021-03-15 13:22 UTC, brusch commented on models/WebsiteSetting.php
> +        $nameCacheKey = $this->getName() . '~~~' . $this->getSiteId() . '~~~' . $this->getLanguage();
I'd leave it as it is for now, as it also has different parameters (just the `id`). Thanks!

2021-03-16 05:33 UTC, merged

2021-03-16 05:33 UTC, brusch commented
LGTM - thanks a lot 👍