[AdminBundle] Mark classes internal/final
pimcore/pimcore pull request #8453
Opened 2021-03-15 13:04 UTC by dvesh3

## Changes in this pull request  
Resolves partially #7189

## Additional info

2021-03-18 14:49 UTC, brusch requested changes

2021-03-18 14:49 UTC, brusch commented on bundles/AdminBundle/Controller/Admin/Document/PageController.php
>  class PageController extends DocumentControllerBase
```suggestion
final class PageController extends DocumentControllerBase
```

2021-03-18 14:49 UTC, brusch commented on bundles/AdminBundle/Controller/Admin/Document/PrintpageControllerBase.php
>  class PrintpageControllerBase extends DocumentControllerBase
```suggestion
abstract class PrintpageControllerBase extends DocumentControllerBase
```

2021-03-18 14:49 UTC, brusch commented on bundles/AdminBundle/Controller/Admin/ElementControllerBase.php
>  class ElementControllerBase extends AdminController
```suggestion
abstract class ElementControllerBase extends AdminController
```

2021-03-18 14:49 UTC, brusch commented on bundles/AdminBundle/Controller/GDPR/PimcoreUsersController.php
>   * @package GDPRDataExtractorBundle\Controller
```suggestion
```

2021-03-18 14:49 UTC, brusch commented on bundles/AdminBundle/Controller/GDPR/SentMailController.php
>   * @package GDPRDataExtractorBundle\Controller
```suggestion
```

2021-03-18 14:49 UTC, brusch commented on bundles/AdminBundle/Controller/Reports/AnalyticsController.php
>  class AnalyticsController extends ReportsControllerBase implements KernelControllerEventInterface
```suggestion
final class AnalyticsController extends ReportsControllerBase implements KernelControllerEventInterface
```

2021-03-18 14:49 UTC, brusch commented on bundles/AdminBundle/Controller/Reports/CustomReportController.php
>  class CustomReportController extends ReportsControllerBase
```suggestion
final class CustomReportController extends ReportsControllerBase
```

2021-03-18 14:49 UTC, brusch commented on bundles/AdminBundle/Controller/Reports/ReportsControllerBase.php
>  class ReportsControllerBase extends AdminController
```suggestion
abstract class ReportsControllerBase extends AdminController
```

2021-03-18 14:49 UTC, brusch commented on bundles/AdminBundle/Controller/Reports/SettingsController.php
>  class SettingsController extends ReportsControllerBase
```suggestion
final class SettingsController extends ReportsControllerBase
```

2021-03-18 14:49 UTC, brusch commented on bundles/AdminBundle/EventListener/CustomAdminEntryPointCheckListener.php
>  class CustomAdminEntryPointCheckListener implements EventSubscriberInterface
```suggestion
final class CustomAdminEntryPointCheckListener implements EventSubscriberInterface
```

2021-03-19 11:42 UTC, brusch approved these changes

2021-03-19 11:43 UTC, merged

2021-05-04 07:14 UTC, roland4432 commented
What's the reason for all classes to be marked as final?

2021-05-04 07:27 UTC, brusch commented
@roland4432 Because they are not intended to be overridden or customized. The BC promise / SemVer doesn't apply to those classes.

2021-05-04 07:43 UTC, roland4432 commented
Could you maybe leave that decission to the programmer?
This breaks dozens of projects and doesn't make any sense in the symfony flow at all.

And.. it doesn't even have the desired effect, since you can still override the controller just not extend it.

2021-05-04 08:11 UTC, roland4432 commented
I am interested what top contributors like @BlackbitNeueMedien @dpfaffenbauer @jdreesen think about that...

2021-05-04 08:44 UTC, BlackbitNeueMedien commented
I never understood the argument to make classes final. Arguments like 
> Using the class for something else by overriding part of its behavior may jeopardize its integrity. The state of the extended object may become unpredictable or inconsistent with the state of the original object.
from https://matthiasnoback.nl/2018/09/final-classes-by-default-why/

are simply not true. If you want to protect internal state of properties, then it is fine for me to make them private. But to prohibit extending a class will only lead to a lot of copy-paste. There are a lot of use-cases where reusing / extending the AdminBundle controllers will on the one hand make custom features easier to implement and on the other hand make them easier to migrate. Because what will happen is that all the custom features which currently extend the AdminBundle controllers which @roland4432 mentions will have to copy the methods from the original classes to still work. Then this at first will work but when those AdminBundle classes get changed, the copied methods might again not work. Of course now you will say that developers have to check their code anyway for Pimcore updates - but what is the advantage of making those classes final?

2021-05-04 09:25 UTC, brusch commented
For me it would be ok as well to just tag them as `@internal`, but that would still mean that we're not maintaining backward-compatibility for those classes - "use at your own risk".

2021-05-04 09:27 UTC, roland4432 commented
Would be totally fine with that.