[Grid Config] Admins should be able to change + delete shared grid configurations
pimcore/pimcore pull request #8549
Opened 2021-03-23 10:30 UTC by BlackbitNeueMedien

Currently only the owner of a shared grid configuration (aka the person who created the grid config) can change and delete it. With this PR also admin users are allowed to change and delete shared grid configurations.

2021-03-24 10:00 UTC, dvesh3 requested changes
still not able to delete shared config by admin. see below:
![image](https://user-images.githubusercontent.com/5137917/112291056-132fa180-8c90-11eb-8b58-80cd5e5c9e91.png)

2021-03-24 11:34 UTC, BlackbitNeueMedien commented on bundles/CoreBundle/Resources/translations/en.json
> +  "userowner": "Owner",
Is `User Owner` clean english? In german this gets translated as `Eigentümer des Benutzers` (= owner of user) - and this is not a proper label for this field.

2021-04-01 07:20 UTC, dvesh3 commented
@BlackbitNeueMedien please see https://github.com/pimcore/pimcore/pull/8549#pullrequestreview-619454953

2021-04-01 08:28 UTC, BlackbitNeueMedien commented
@dvesh3 could you tell me how to reproduce your state?
I just tried it again by doing the following:
1. Ensure you are logged-in with user `admin` who is an administrator
2. Go to a data object folder, click `Grid Options`, go to `Save & Share` panel, enter `name` "test", check `Share globally` and click `Copy & Share` button
3. Create user `test` who is also an administrator
4. log in with user `test` go to folder from 2., select `test` in `Grid Options` button's dropdown
5. Expand `Grid Options` button's dropdown again and in my case `Delete` is possible

2021-04-01 09:27 UTC, dvesh3 commented
@BlackbitNeueMedien I used `shared user` option to share with administrator user, instead of `Share globally`.

2021-04-08 10:07 UTC, brusch commented
@BlackbitNeueMedien  any updates on this? Thanks 😊

2021-04-15 07:12 UTC, dvesh3 commented
🏓 @BlackbitNeueMedien

2021-04-15 08:13 UTC, BlackbitNeueMedien commented
@dvesh3 Should work now also for configurations which are shared with users or roles (and not globally).

2021-04-16 06:21 UTC, dvesh3 approved these changes

2021-04-16 06:22 UTC, merged

2021-04-16 06:22 UTC, dvesh3 commented
@BlackbitNeueMedien thanks a lot!