[Data object grid] Prevent ambiguous columns when filtering / sorting by object brick field
pimcore/pimcore pull request #8829
Opened 2021-04-19 08:32 UTC by BlackbitNeueMedien

Steps to reproduce problem:
1. Create class `Product`. Add a `select` field `test` and option `A`and `B`. Add an object brick field named `bricks`.
2. Create an object brick `Brick`. Add a `select` field `test` and option `A`and `B`. Assign `Product.bricks` as allowed brick field.
3. Create an object `/A` of class `Product`, assign object brick `Brick`, select `A` in `Brick.test`.
4. Click `Home` in data object tree, click `Grid options` add field `test` from object brick `Brick`
5. Sort by field `test` -> first ambigous column error appears
6. Filter by field `test=A` -> second ambigous column error appears

This PR prefixes the sort / filter field names with the brick table alias.

2021-04-22 10:29 UTC, dvesh3 requested changes
ambiguous column error appears when sorting direct field "test" along with brick field "test"

2021-04-26 08:36 UTC, dvesh3 commented
@BlackbitNeueMedien please see https://github.com/pimcore/pimcore/pull/8829#pullrequestreview-642034828

2021-04-27 07:57 UTC, BlackbitNeueMedien commented
Now filtering and sorting does work for the class field and for the brick field.

2021-04-28 09:11 UTC, merged

2021-04-28 09:11 UTC, dvesh3 commented
thanks a lot!