Prepared statements for Classificationstore groups fix
pimcore/pimcore pull request #8872
Opened 2021-04-23 08:23 UTC by NiklasBr

## Changes in this pull request  
Resolves #8865

2021-04-23 09:12 UTC, jdreesen requested changes

2021-04-23 09:12 UTC, jdreesen commented on models/DataObject/ClassDefinition/Data/Classificationstore.php
> +        $groupList->setCondition('`id` in (' . implode(',', array_map(function ($id) { return '?'; }, $filteredGroupIds)) . ')', $filteredGroupIds);
```suggestion
        $groupList->setCondition('`id` in (' . implode(',', array_fill(0, count($filteredGroupIds), '?')) . ')', $filteredGroupIds);
```

2021-04-23 09:12 UTC, jdreesen commented on models/DataObject/ClassDefinition/Data/Classificationstore.php
> +            $relation->setCondition('`colId` in (' . implode(',', array_map(function ($id) { return '?'; }, $collectionIds)) . ')', $collectionIds);
```suggestion
            $relation->setCondition('`colId` in (' . implode(',', array_fill(0, count($collectionIds), '?')) . ')', $collectionIds);
```

2021-04-23 09:35 UTC, NiklasBr commented
Thanks @jdreesen!

2021-04-23 13:51 UTC, jdreesen commented
Note that target branch and milestone currently differ.

2021-04-23 15:38 UTC, NiklasBr commented
Yes, I targeted the wrong branch at first.

2021-04-26 07:45 UTC, merged

2021-04-26 08:11 UTC, jdreesen commented
@weisswurstkanone you should probably adjust the milestone...