Redirect CSV export needs same handling as RedirectHandler
pimcore/pimcore pull request #9418
Opened 2021-06-11 12:36 UTC by Daniel-Ateles

Because the CSV-export is not a site request the function Document->getFullPath will return the target with the root document path.
I essentially copied what the RedirectHandler does.
(The same problem exists for RedirectController that shows the wrong target for auto-created redirects)

  
  

## Changes in this pull request  
Resolves #

## Additional info

2021-06-16 08:43 UTC, dvesh3 requested changes
we should also fix site specific targets for auto-created redirects in `RedirectController`

2021-06-16 08:43 UTC, dvesh3 commented on lib/Routing/Redirect/Csv.php
> +                    $rootDocument = $targetSite->getRootDocument();
this will break csv export when exporting main site entries where targetSite is null

2021-06-18 07:41 UTC, dvesh3 commented
@Daniel-Ateles could you please fix this https://github.com/pimcore/pimcore/pull/9418#pullrequestreview-684888130? thanks!

2021-06-21 07:17 UTC, Daniel-Ateles commented
> @Daniel-Ateles could you please fix this [#9418 (review)](https://github.com/pimcore/pimcore/pull/9418#pullrequestreview-684888130)? thanks!

Will hopefuly start looking on it today.

2021-06-21 07:23 UTC, dvesh3 commented
> > @Daniel-Ateles could you please fix this [#9418 (review)](https://github.com/pimcore/pimcore/pull/9418#pullrequestreview-684888130)? thanks!
> 
> Will hopefuly start looking on it today.

sounds good! just an heads up that the release 6.9.6 (last release for 6.x) is planned for 23rd June.

2021-06-22 10:17 UTC, Daniel-Ateles commented
> we should also fix site specific targets for auto-created redirects in `RedirectController`

New PR for the controller: https://github.com/pimcore/pimcore/pull/9523

2021-06-22 13:51 UTC, brusch commented
As this PR is now it would break the import. 
See also my comment here: https://github.com/pimcore/pimcore/pull/9523#issuecomment-865954020 

So I'd leave it as is is or include the main domain of the site, so that it is clear to which document the redirect refers to. The we'd also need to consider this in the import and also discuss which protocol should be used.

2021-06-22 13:53 UTC, brusch commented
I'll close this for now, as it isn't anyway a bug and therefore not relevant for `6.9`. 
However we can continue the discussion how we can improve that for `10.x` (considering my thoughts from above). 
Thanks!

2021-06-22 13:53 UTC, closed without merging