Quicksearch: use class icons when available
pimcore/pimcore pull request #9498
Opened 2021-06-18 17:28 UTC by NiklasBr

## Changes in this pull request  
Show custom class icon in quicksearch for root products (variants still keep their icon)

## Additional info  

![image](https://user-images.githubusercontent.com/279826/122597133-3c7f8400-d06b-11eb-9fa2-3eeb9b0fb0f7.png)

2021-06-21 08:52 UTC, NiklasBr commented
These errors make no sense considering the changes:
```log
Error: ] Found 21 errors                                                        

Error: Instantiated class Google_Service_Customsearch not found.
Error: Access to property $cse on an unknown class Google_Service_Customsearch.
Error: Parameter $googleResponse of method Pimcore\Google\Cse::readGoogleResponse() has invalid typehint type Google_Service_Customsearch_Search.
Error: Parameter $googleResponse of method Pimcore\Google\Cse::readGoogleResponse() has invalid typehint type Google_Service_Customsearch_Search.
Error: Call to method getSearchInformation() on an unknown class Google_Service_Customsearch_Search.
Error: Call to method getItems() on an unknown class Google_Service_Customsearch_Search.
Error: PHPDoc tag @var for variable $results contains unknown class Google_Service_Customsearch_Result.
Error: Call to method getPagemap() on an unknown class Google_Service_Customsearch_Result.
Error: Access to offset 'pagemap' on an unknown class Google_Service_Customsearch_Result.
Error: Access to offset 'pagemap' on an unknown class Google_Service_Customsearch_Result.
Error: Access to offset 'pagemap' on an unknown class Google_Service_Customsearch_Result.
Error: Access to offset 'pagemap' on an unknown class Google_Service_Customsearch_Result.
Error: Access to offset 'pagemap' on an unknown class Google_Service_Customsearch_Result.
Error: Call to method getLink() on an unknown class Google_Service_Customsearch_Result.
Error: Property Pimcore\Google\Cse\Item::$raw has unknown class Google_Service_Customsearch_Result as its type.
Error: Parameter $data of method Pimcore\Google\Cse\Item::__construct() has invalid typehint type Google_Service_Customsearch_Result.
Error: Parameter $data of method Pimcore\Google\Cse\Item::__construct() has invalid typehint type Google_Service_Customsearch_Result.
Error: Parameter $data of method Pimcore\Google\Cse\Item::setValues() has invalid typehint type Google_Service_Customsearch_Result.
Error: Parameter $data of method Pimcore\Google\Cse\Item::setValues() has invalid typehint type Google_Service_Customsearch_Result.
Error: Parameter $raw of method Pimcore\Google\Cse\Item::setRaw() has invalid typehint type Google_Service_Customsearch_Result.
Error: Return typehint of method Pimcore\Google\Cse\Item::getRaw() has invalid type Google_Service_Customsearch_Result.
Error: Process completed with exit code 1.
```

2021-06-21 08:55 UTC, dvesh3 commented
@NiklasBr seems like they changed the namespace in `googleapis/google-api-php-client-services` on v2 so stan is unable to find the class. we are on it!

2021-06-23 08:26 UTC, brusch requested changes

2021-06-23 08:26 UTC, brusch commented on bundles/AdminBundle/Controller/Searchadmin/SearchController.php
> +                    if ($element->getType() === DataObject::OBJECT_TYPE_OBJECT && $element->getClass()->getIcon()) {
I think we should use the same concept here as we do for the tree, see: https://github.com/pimcore/pimcore/blob/2f18a0f26380c56b609d937b40d2050c8d1a3e1a/bundles/AdminBundle/Controller/Traits/AdminStyleTrait.php#L37

2021-06-30 19:54 UTC, closed without merging

2021-06-30 19:54 UTC, NiklasBr commented
Rebase:ing is the bane of my existence.