[Mail] First log to "Sent mails" then try to send
pimcore/pimcore pull request #9553
Opened 2021-06-24 06:33 UTC by BlackbitNeueMedien

This PR changes the order of processing when emails are sent via `\Pimcore\Mail`. The problem currently is that when you call the `send()` method that it is first tries to send the mail and only if this was successful the mail is logged / saved to "Sent mails" in Pimcore backend:
https://github.com/pimcore/pimcore/blob/d37fd30fa0768adeebd5161e8c8df07e0df3e88b/lib/Mail.php#L548-L573

The problem is when you recognize in your application code that no mail has been sent you do not know if your application is wrong or if the email configuration is wrong. With this PR the mail to be sent is first logged to "Sent mails". This way even when mail configuration is wrong and the mail cannot be sent, you see that at least it was tried to be sent in the "Sent mails".

2021-06-24 06:38 UTC, fashxp commented
hmm, but then its not a sent mails log anymore... ;-)
I guess, then we also would need to add a flag that indicates if sending was possible or not...

2021-06-24 07:40 UTC, BlackbitNeueMedien commented
You are right, @fashxp - I implemented a more sophisticated solution. Now there is a new icon in the "Sent Mails" panel. When you click it you see the error which happened during sending. If errors occured the whole line in the grid gets red background:
<img width="1678" alt="Bildschirmfoto 2021-06-24 um 09 38 42" src="https://user-images.githubusercontent.com/8749138/123222394-3147b080-d4d0-11eb-89ba-c612a83b7476.png">

<img width="1683" alt="Bildschirmfoto 2021-06-24 um 09 38 48" src="https://user-images.githubusercontent.com/8749138/123222410-3573ce00-d4d0-11eb-87b7-899be65a698e.png">

2021-07-01 08:37 UTC, dvesh3 commented on models/Tool/Email/Log.php
> +     * Error which happened when mail got sent - empty if no error occured
```suggestion
     * Error log, when mail send resulted in failure - empty if successfully sent
```

2021-07-01 08:43 UTC, dvesh3 requested changes
I assume "forward" and "resend" options are disabled for the failed logs, since this will lead to same the error.

2021-07-01 08:48 UTC, BlackbitNeueMedien commented
Especially for mails with errors I would not disable "resend" because when the error is about a wrnig SMTP configuration or something else with the mail server, this "resend" allows to send the mails again after the infrastrcuture problem has been fixed.

2021-07-01 08:52 UTC, dvesh3 commented
> Especially for mails with errors I would not disable "resend" because when the error is about a wrnig SMTP configuration or something else with the mail server, this "resend" allows to send the mails again after the infrastrcuture problem has been fixed.

yes, that's a valid point. 👍

2021-07-01 08:52 UTC, dvesh3 approved these changes

2021-07-01 09:41 UTC, dvesh3 commented
@BlackbitNeueMedien for  "wrong SMTP configuration" exception handling we need to refactor the mail class. As it will throw exception when loading mailer from the container, so here https://github.com/pimcore/pimcore/blob/10.x/lib/Mail.php#L534 (which is not in try catch) and moreover, we are catching only `TransportExceptionInterface` related to send() not `InvalidArgumentException`.

2021-07-01 10:49 UTC, BlackbitNeueMedien commented
Ok, now all exceptions get caught.

2021-07-02 07:28 UTC, merged

2021-07-02 07:29 UTC, dvesh3 commented
@BlackbitNeueMedien Nice improvement 👍  thanks a lot!