Fix: ObjectBrick with multiple Localized fields are broken after update to 6.9/10.0
pimcore/pimcore pull request #9654
Opened 2021-07-02 06:42 UTC by blankse

Resolve #9646

2021-07-02 07:14 UTC, blankse commented
Classificationstore has also setReferencedFields/addReferencedField but no getFieldDefinitions method which call getReferencedFields. Is it there still needed?

2021-07-05 15:20 UTC, dvesh3 requested changes
since this needs to regenerate brick tables...please add migration to save objectbricks

2021-07-06 07:21 UTC, dvesh3 commented on bundles/CoreBundle/Migrations/Version20210706090823.php
> +        return '';
```suggestion
        return 'Rebuild class definitions to fix Objectbricks with multiple Localized fields';
```

2021-07-06 07:37 UTC, merged

2021-07-06 07:37 UTC, dvesh3 commented
@blankse thanks a lot!